// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: admiral/api/user/v1/user.proto

package userv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "go.admiral.io/sdk/proto/admiral/api/user/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserAPIName is the fully-qualified name of the UserAPI service.
	UserAPIName = "admiral.api.user.v1.UserAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserAPIGetUserProcedure is the fully-qualified name of the UserAPI's GetUser RPC.
	UserAPIGetUserProcedure = "/admiral.api.user.v1.UserAPI/GetUser"
	// UserAPICreatePersonalAccessTokenProcedure is the fully-qualified name of the UserAPI's
	// CreatePersonalAccessToken RPC.
	UserAPICreatePersonalAccessTokenProcedure = "/admiral.api.user.v1.UserAPI/CreatePersonalAccessToken"
	// UserAPIListPersonalAccessTokensProcedure is the fully-qualified name of the UserAPI's
	// ListPersonalAccessTokens RPC.
	UserAPIListPersonalAccessTokensProcedure = "/admiral.api.user.v1.UserAPI/ListPersonalAccessTokens"
	// UserAPIGetPersonalAccessTokenProcedure is the fully-qualified name of the UserAPI's
	// GetPersonalAccessToken RPC.
	UserAPIGetPersonalAccessTokenProcedure = "/admiral.api.user.v1.UserAPI/GetPersonalAccessToken"
	// UserAPIRevokePersonalAccessTokenProcedure is the fully-qualified name of the UserAPI's
	// RevokePersonalAccessToken RPC.
	UserAPIRevokePersonalAccessTokenProcedure = "/admiral.api.user.v1.UserAPI/RevokePersonalAccessToken"
)

// UserAPIClient is a client for the admiral.api.user.v1.UserAPI service.
type UserAPIClient interface {
	// GetUser retrieves the profile of the currently authenticated user.
	// The user is identified by the authentication token provided in the request.
	GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error)
	// CreatePersonalAccessToken creates a new PAT for the authenticated user.
	// The response includes the raw token secret, which is shown exactly once
	// and cannot be retrieved again.
	//
	// Scope: `token:write`
	CreatePersonalAccessToken(context.Context, *connect.Request[v1.CreatePersonalAccessTokenRequest]) (*connect.Response[v1.CreatePersonalAccessTokenResponse], error)
	// ListPersonalAccessTokens returns a paginated list of the authenticated
	// user's PATs. Token secrets are never included.
	//
	// Scope: `token:read`
	ListPersonalAccessTokens(context.Context, *connect.Request[v1.ListPersonalAccessTokensRequest]) (*connect.Response[v1.ListPersonalAccessTokensResponse], error)
	// GetPersonalAccessToken retrieves a single PAT by ID.
	// Returns metadata only -- the token secret is never included.
	//
	// Scope: `token:read`
	GetPersonalAccessToken(context.Context, *connect.Request[v1.GetPersonalAccessTokenRequest]) (*connect.Response[v1.GetPersonalAccessTokenResponse], error)
	// RevokePersonalAccessToken permanently revokes a PAT. The token becomes
	// immediately unusable and cannot be restored.
	//
	// Scope: `token:write`
	RevokePersonalAccessToken(context.Context, *connect.Request[v1.RevokePersonalAccessTokenRequest]) (*connect.Response[v1.RevokePersonalAccessTokenResponse], error)
}

// NewUserAPIClient constructs a client for the admiral.api.user.v1.UserAPI service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userAPIMethods := v1.File_admiral_api_user_v1_user_proto.Services().ByName("UserAPI").Methods()
	return &userAPIClient{
		getUser: connect.NewClient[v1.GetUserRequest, v1.GetUserResponse](
			httpClient,
			baseURL+UserAPIGetUserProcedure,
			connect.WithSchema(userAPIMethods.ByName("GetUser")),
			connect.WithClientOptions(opts...),
		),
		createPersonalAccessToken: connect.NewClient[v1.CreatePersonalAccessTokenRequest, v1.CreatePersonalAccessTokenResponse](
			httpClient,
			baseURL+UserAPICreatePersonalAccessTokenProcedure,
			connect.WithSchema(userAPIMethods.ByName("CreatePersonalAccessToken")),
			connect.WithClientOptions(opts...),
		),
		listPersonalAccessTokens: connect.NewClient[v1.ListPersonalAccessTokensRequest, v1.ListPersonalAccessTokensResponse](
			httpClient,
			baseURL+UserAPIListPersonalAccessTokensProcedure,
			connect.WithSchema(userAPIMethods.ByName("ListPersonalAccessTokens")),
			connect.WithClientOptions(opts...),
		),
		getPersonalAccessToken: connect.NewClient[v1.GetPersonalAccessTokenRequest, v1.GetPersonalAccessTokenResponse](
			httpClient,
			baseURL+UserAPIGetPersonalAccessTokenProcedure,
			connect.WithSchema(userAPIMethods.ByName("GetPersonalAccessToken")),
			connect.WithClientOptions(opts...),
		),
		revokePersonalAccessToken: connect.NewClient[v1.RevokePersonalAccessTokenRequest, v1.RevokePersonalAccessTokenResponse](
			httpClient,
			baseURL+UserAPIRevokePersonalAccessTokenProcedure,
			connect.WithSchema(userAPIMethods.ByName("RevokePersonalAccessToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userAPIClient implements UserAPIClient.
type userAPIClient struct {
	getUser                   *connect.Client[v1.GetUserRequest, v1.GetUserResponse]
	createPersonalAccessToken *connect.Client[v1.CreatePersonalAccessTokenRequest, v1.CreatePersonalAccessTokenResponse]
	listPersonalAccessTokens  *connect.Client[v1.ListPersonalAccessTokensRequest, v1.ListPersonalAccessTokensResponse]
	getPersonalAccessToken    *connect.Client[v1.GetPersonalAccessTokenRequest, v1.GetPersonalAccessTokenResponse]
	revokePersonalAccessToken *connect.Client[v1.RevokePersonalAccessTokenRequest, v1.RevokePersonalAccessTokenResponse]
}

// GetUser calls admiral.api.user.v1.UserAPI.GetUser.
func (c *userAPIClient) GetUser(ctx context.Context, req *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error) {
	return c.getUser.CallUnary(ctx, req)
}

// CreatePersonalAccessToken calls admiral.api.user.v1.UserAPI.CreatePersonalAccessToken.
func (c *userAPIClient) CreatePersonalAccessToken(ctx context.Context, req *connect.Request[v1.CreatePersonalAccessTokenRequest]) (*connect.Response[v1.CreatePersonalAccessTokenResponse], error) {
	return c.createPersonalAccessToken.CallUnary(ctx, req)
}

// ListPersonalAccessTokens calls admiral.api.user.v1.UserAPI.ListPersonalAccessTokens.
func (c *userAPIClient) ListPersonalAccessTokens(ctx context.Context, req *connect.Request[v1.ListPersonalAccessTokensRequest]) (*connect.Response[v1.ListPersonalAccessTokensResponse], error) {
	return c.listPersonalAccessTokens.CallUnary(ctx, req)
}

// GetPersonalAccessToken calls admiral.api.user.v1.UserAPI.GetPersonalAccessToken.
func (c *userAPIClient) GetPersonalAccessToken(ctx context.Context, req *connect.Request[v1.GetPersonalAccessTokenRequest]) (*connect.Response[v1.GetPersonalAccessTokenResponse], error) {
	return c.getPersonalAccessToken.CallUnary(ctx, req)
}

// RevokePersonalAccessToken calls admiral.api.user.v1.UserAPI.RevokePersonalAccessToken.
func (c *userAPIClient) RevokePersonalAccessToken(ctx context.Context, req *connect.Request[v1.RevokePersonalAccessTokenRequest]) (*connect.Response[v1.RevokePersonalAccessTokenResponse], error) {
	return c.revokePersonalAccessToken.CallUnary(ctx, req)
}

// UserAPIHandler is an implementation of the admiral.api.user.v1.UserAPI service.
type UserAPIHandler interface {
	// GetUser retrieves the profile of the currently authenticated user.
	// The user is identified by the authentication token provided in the request.
	GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error)
	// CreatePersonalAccessToken creates a new PAT for the authenticated user.
	// The response includes the raw token secret, which is shown exactly once
	// and cannot be retrieved again.
	//
	// Scope: `token:write`
	CreatePersonalAccessToken(context.Context, *connect.Request[v1.CreatePersonalAccessTokenRequest]) (*connect.Response[v1.CreatePersonalAccessTokenResponse], error)
	// ListPersonalAccessTokens returns a paginated list of the authenticated
	// user's PATs. Token secrets are never included.
	//
	// Scope: `token:read`
	ListPersonalAccessTokens(context.Context, *connect.Request[v1.ListPersonalAccessTokensRequest]) (*connect.Response[v1.ListPersonalAccessTokensResponse], error)
	// GetPersonalAccessToken retrieves a single PAT by ID.
	// Returns metadata only -- the token secret is never included.
	//
	// Scope: `token:read`
	GetPersonalAccessToken(context.Context, *connect.Request[v1.GetPersonalAccessTokenRequest]) (*connect.Response[v1.GetPersonalAccessTokenResponse], error)
	// RevokePersonalAccessToken permanently revokes a PAT. The token becomes
	// immediately unusable and cannot be restored.
	//
	// Scope: `token:write`
	RevokePersonalAccessToken(context.Context, *connect.Request[v1.RevokePersonalAccessTokenRequest]) (*connect.Response[v1.RevokePersonalAccessTokenResponse], error)
}

// NewUserAPIHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserAPIHandler(svc UserAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userAPIMethods := v1.File_admiral_api_user_v1_user_proto.Services().ByName("UserAPI").Methods()
	userAPIGetUserHandler := connect.NewUnaryHandler(
		UserAPIGetUserProcedure,
		svc.GetUser,
		connect.WithSchema(userAPIMethods.ByName("GetUser")),
		connect.WithHandlerOptions(opts...),
	)
	userAPICreatePersonalAccessTokenHandler := connect.NewUnaryHandler(
		UserAPICreatePersonalAccessTokenProcedure,
		svc.CreatePersonalAccessToken,
		connect.WithSchema(userAPIMethods.ByName("CreatePersonalAccessToken")),
		connect.WithHandlerOptions(opts...),
	)
	userAPIListPersonalAccessTokensHandler := connect.NewUnaryHandler(
		UserAPIListPersonalAccessTokensProcedure,
		svc.ListPersonalAccessTokens,
		connect.WithSchema(userAPIMethods.ByName("ListPersonalAccessTokens")),
		connect.WithHandlerOptions(opts...),
	)
	userAPIGetPersonalAccessTokenHandler := connect.NewUnaryHandler(
		UserAPIGetPersonalAccessTokenProcedure,
		svc.GetPersonalAccessToken,
		connect.WithSchema(userAPIMethods.ByName("GetPersonalAccessToken")),
		connect.WithHandlerOptions(opts...),
	)
	userAPIRevokePersonalAccessTokenHandler := connect.NewUnaryHandler(
		UserAPIRevokePersonalAccessTokenProcedure,
		svc.RevokePersonalAccessToken,
		connect.WithSchema(userAPIMethods.ByName("RevokePersonalAccessToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/admiral.api.user.v1.UserAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserAPIGetUserProcedure:
			userAPIGetUserHandler.ServeHTTP(w, r)
		case UserAPICreatePersonalAccessTokenProcedure:
			userAPICreatePersonalAccessTokenHandler.ServeHTTP(w, r)
		case UserAPIListPersonalAccessTokensProcedure:
			userAPIListPersonalAccessTokensHandler.ServeHTTP(w, r)
		case UserAPIGetPersonalAccessTokenProcedure:
			userAPIGetPersonalAccessTokenHandler.ServeHTTP(w, r)
		case UserAPIRevokePersonalAccessTokenProcedure:
			userAPIRevokePersonalAccessTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedUserAPIHandler struct{}

func (UnimplementedUserAPIHandler) GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.user.v1.UserAPI.GetUser is not implemented"))
}

func (UnimplementedUserAPIHandler) CreatePersonalAccessToken(context.Context, *connect.Request[v1.CreatePersonalAccessTokenRequest]) (*connect.Response[v1.CreatePersonalAccessTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.user.v1.UserAPI.CreatePersonalAccessToken is not implemented"))
}

func (UnimplementedUserAPIHandler) ListPersonalAccessTokens(context.Context, *connect.Request[v1.ListPersonalAccessTokensRequest]) (*connect.Response[v1.ListPersonalAccessTokensResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.user.v1.UserAPI.ListPersonalAccessTokens is not implemented"))
}

func (UnimplementedUserAPIHandler) GetPersonalAccessToken(context.Context, *connect.Request[v1.GetPersonalAccessTokenRequest]) (*connect.Response[v1.GetPersonalAccessTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.user.v1.UserAPI.GetPersonalAccessToken is not implemented"))
}

func (UnimplementedUserAPIHandler) RevokePersonalAccessToken(context.Context, *connect.Request[v1.RevokePersonalAccessTokenRequest]) (*connect.Response[v1.RevokePersonalAccessTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.user.v1.UserAPI.RevokePersonalAccessToken is not implemented"))
}
