// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admiral/deployment/v1/deployment.proto

package deploymentv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Deployment with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Deployment) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Deployment with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DeploymentMultiError, or
// nil if none found.
func (m *Deployment) ValidateAll() error {
	return m.validate(true)
}

func (m *Deployment) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ApplicationId

	// no validation rules for EnvironmentId

	// no validation rules for Status

	// no validation rules for TriggerType

	// no validation rules for TriggeredBy

	// no validation rules for Message

	// no validation rules for Destroy

	if all {
		switch v := interface{}(m.GetRevisionSummary()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeploymentValidationError{
					field:  "RevisionSummary",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeploymentValidationError{
					field:  "RevisionSummary",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRevisionSummary()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeploymentValidationError{
				field:  "RevisionSummary",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeploymentValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeploymentValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeploymentValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCompletedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeploymentValidationError{
					field:  "CompletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeploymentValidationError{
					field:  "CompletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCompletedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeploymentValidationError{
				field:  "CompletedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DeploymentMultiError(errors)
	}

	return nil
}

// DeploymentMultiError is an error wrapping multiple validation errors
// returned by Deployment.ValidateAll() if the designated constraints aren't met.
type DeploymentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeploymentMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeploymentMultiError) AllErrors() []error { return m }

// DeploymentValidationError is the validation error returned by
// Deployment.Validate if the designated constraints aren't met.
type DeploymentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeploymentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeploymentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeploymentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeploymentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeploymentValidationError) ErrorName() string { return "DeploymentValidationError" }

// Error satisfies the builtin error interface
func (e DeploymentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeployment.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeploymentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeploymentValidationError{}

// Validate checks the field values on RevisionSummary with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RevisionSummary) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RevisionSummary with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RevisionSummaryMultiError, or nil if none found.
func (m *RevisionSummary) ValidateAll() error {
	return m.validate(true)
}

func (m *RevisionSummary) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	// no validation rules for Succeeded

	// no validation rules for Failed

	// no validation rules for Blocked

	// no validation rules for Running

	// no validation rules for Cancelled

	// no validation rules for Pending

	if len(errors) > 0 {
		return RevisionSummaryMultiError(errors)
	}

	return nil
}

// RevisionSummaryMultiError is an error wrapping multiple validation errors
// returned by RevisionSummary.ValidateAll() if the designated constraints
// aren't met.
type RevisionSummaryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RevisionSummaryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RevisionSummaryMultiError) AllErrors() []error { return m }

// RevisionSummaryValidationError is the validation error returned by
// RevisionSummary.Validate if the designated constraints aren't met.
type RevisionSummaryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RevisionSummaryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RevisionSummaryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RevisionSummaryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RevisionSummaryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RevisionSummaryValidationError) ErrorName() string { return "RevisionSummaryValidationError" }

// Error satisfies the builtin error interface
func (e RevisionSummaryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRevisionSummary.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RevisionSummaryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RevisionSummaryValidationError{}

// Validate checks the field values on Revision with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Revision) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Revision with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RevisionMultiError, or nil
// if none found.
func (m *Revision) ValidateAll() error {
	return m.validate(true)
}

func (m *Revision) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for DeploymentId

	// no validation rules for ComponentId

	// no validation rules for ComponentName

	// no validation rules for Category

	// no validation rules for Status

	// no validation rules for SourceId

	// no validation rules for Version

	// no validation rules for ResolvedValues

	// no validation rules for ArtifactChecksum

	// no validation rules for ArtifactUrl

	// no validation rules for PlanOutput

	if all {
		switch v := interface{}(m.GetPlanSummary()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RevisionValidationError{
					field:  "PlanSummary",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RevisionValidationError{
					field:  "PlanSummary",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPlanSummary()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RevisionValidationError{
				field:  "PlanSummary",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ErrorMessage

	// no validation rules for RetryCount

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RevisionValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RevisionValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RevisionValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetStartedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RevisionValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RevisionValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RevisionValidationError{
				field:  "StartedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCompletedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RevisionValidationError{
					field:  "CompletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RevisionValidationError{
					field:  "CompletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCompletedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RevisionValidationError{
				field:  "CompletedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RevisionMultiError(errors)
	}

	return nil
}

// RevisionMultiError is an error wrapping multiple validation errors returned
// by Revision.ValidateAll() if the designated constraints aren't met.
type RevisionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RevisionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RevisionMultiError) AllErrors() []error { return m }

// RevisionValidationError is the validation error returned by
// Revision.Validate if the designated constraints aren't met.
type RevisionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RevisionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RevisionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RevisionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RevisionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RevisionValidationError) ErrorName() string { return "RevisionValidationError" }

// Error satisfies the builtin error interface
func (e RevisionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRevision.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RevisionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RevisionValidationError{}

// Validate checks the field values on TerraformPlanSummary with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TerraformPlanSummary) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TerraformPlanSummary with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TerraformPlanSummaryMultiError, or nil if none found.
func (m *TerraformPlanSummary) ValidateAll() error {
	return m.validate(true)
}

func (m *TerraformPlanSummary) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Additions

	// no validation rules for Changes

	// no validation rules for Destructions

	if len(errors) > 0 {
		return TerraformPlanSummaryMultiError(errors)
	}

	return nil
}

// TerraformPlanSummaryMultiError is an error wrapping multiple validation
// errors returned by TerraformPlanSummary.ValidateAll() if the designated
// constraints aren't met.
type TerraformPlanSummaryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TerraformPlanSummaryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TerraformPlanSummaryMultiError) AllErrors() []error { return m }

// TerraformPlanSummaryValidationError is the validation error returned by
// TerraformPlanSummary.Validate if the designated constraints aren't met.
type TerraformPlanSummaryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TerraformPlanSummaryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TerraformPlanSummaryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TerraformPlanSummaryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TerraformPlanSummaryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TerraformPlanSummaryValidationError) ErrorName() string {
	return "TerraformPlanSummaryValidationError"
}

// Error satisfies the builtin error interface
func (e TerraformPlanSummaryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTerraformPlanSummary.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TerraformPlanSummaryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TerraformPlanSummaryValidationError{}

// Validate checks the field values on CreateDeploymentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateDeploymentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateDeploymentRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateDeploymentRequestMultiError, or nil if none found.
func (m *CreateDeploymentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateDeploymentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ApplicationId

	// no validation rules for EnvironmentId

	// no validation rules for Message

	// no validation rules for Destroy

	if len(errors) > 0 {
		return CreateDeploymentRequestMultiError(errors)
	}

	return nil
}

// CreateDeploymentRequestMultiError is an error wrapping multiple validation
// errors returned by CreateDeploymentRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateDeploymentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateDeploymentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateDeploymentRequestMultiError) AllErrors() []error { return m }

// CreateDeploymentRequestValidationError is the validation error returned by
// CreateDeploymentRequest.Validate if the designated constraints aren't met.
type CreateDeploymentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateDeploymentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateDeploymentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateDeploymentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateDeploymentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateDeploymentRequestValidationError) ErrorName() string {
	return "CreateDeploymentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateDeploymentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateDeploymentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateDeploymentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateDeploymentRequestValidationError{}

// Validate checks the field values on CreateDeploymentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateDeploymentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateDeploymentResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateDeploymentResponseMultiError, or nil if none found.
func (m *CreateDeploymentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateDeploymentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDeployment()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateDeploymentResponseValidationError{
					field:  "Deployment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateDeploymentResponseValidationError{
					field:  "Deployment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDeployment()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateDeploymentResponseValidationError{
				field:  "Deployment",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateDeploymentResponseMultiError(errors)
	}

	return nil
}

// CreateDeploymentResponseMultiError is an error wrapping multiple validation
// errors returned by CreateDeploymentResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateDeploymentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateDeploymentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateDeploymentResponseMultiError) AllErrors() []error { return m }

// CreateDeploymentResponseValidationError is the validation error returned by
// CreateDeploymentResponse.Validate if the designated constraints aren't met.
type CreateDeploymentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateDeploymentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateDeploymentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateDeploymentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateDeploymentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateDeploymentResponseValidationError) ErrorName() string {
	return "CreateDeploymentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateDeploymentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateDeploymentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateDeploymentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateDeploymentResponseValidationError{}

// Validate checks the field values on GetDeploymentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetDeploymentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDeploymentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDeploymentRequestMultiError, or nil if none found.
func (m *GetDeploymentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDeploymentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DeploymentId

	if len(errors) > 0 {
		return GetDeploymentRequestMultiError(errors)
	}

	return nil
}

// GetDeploymentRequestMultiError is an error wrapping multiple validation
// errors returned by GetDeploymentRequest.ValidateAll() if the designated
// constraints aren't met.
type GetDeploymentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDeploymentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDeploymentRequestMultiError) AllErrors() []error { return m }

// GetDeploymentRequestValidationError is the validation error returned by
// GetDeploymentRequest.Validate if the designated constraints aren't met.
type GetDeploymentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDeploymentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDeploymentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDeploymentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDeploymentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDeploymentRequestValidationError) ErrorName() string {
	return "GetDeploymentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetDeploymentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDeploymentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDeploymentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDeploymentRequestValidationError{}

// Validate checks the field values on GetDeploymentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetDeploymentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDeploymentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDeploymentResponseMultiError, or nil if none found.
func (m *GetDeploymentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDeploymentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDeployment()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetDeploymentResponseValidationError{
					field:  "Deployment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetDeploymentResponseValidationError{
					field:  "Deployment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDeployment()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetDeploymentResponseValidationError{
				field:  "Deployment",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetDeploymentResponseMultiError(errors)
	}

	return nil
}

// GetDeploymentResponseMultiError is an error wrapping multiple validation
// errors returned by GetDeploymentResponse.ValidateAll() if the designated
// constraints aren't met.
type GetDeploymentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDeploymentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDeploymentResponseMultiError) AllErrors() []error { return m }

// GetDeploymentResponseValidationError is the validation error returned by
// GetDeploymentResponse.Validate if the designated constraints aren't met.
type GetDeploymentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDeploymentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDeploymentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDeploymentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDeploymentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDeploymentResponseValidationError) ErrorName() string {
	return "GetDeploymentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetDeploymentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDeploymentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDeploymentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDeploymentResponseValidationError{}

// Validate checks the field values on ListDeploymentsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListDeploymentsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListDeploymentsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListDeploymentsRequestMultiError, or nil if none found.
func (m *ListDeploymentsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListDeploymentsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Filter

	// no validation rules for PageSize

	// no validation rules for PageToken

	if len(errors) > 0 {
		return ListDeploymentsRequestMultiError(errors)
	}

	return nil
}

// ListDeploymentsRequestMultiError is an error wrapping multiple validation
// errors returned by ListDeploymentsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListDeploymentsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListDeploymentsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListDeploymentsRequestMultiError) AllErrors() []error { return m }

// ListDeploymentsRequestValidationError is the validation error returned by
// ListDeploymentsRequest.Validate if the designated constraints aren't met.
type ListDeploymentsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListDeploymentsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListDeploymentsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListDeploymentsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListDeploymentsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListDeploymentsRequestValidationError) ErrorName() string {
	return "ListDeploymentsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListDeploymentsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListDeploymentsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListDeploymentsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListDeploymentsRequestValidationError{}

// Validate checks the field values on ListDeploymentsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListDeploymentsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListDeploymentsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListDeploymentsResponseMultiError, or nil if none found.
func (m *ListDeploymentsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListDeploymentsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetDeployments() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListDeploymentsResponseValidationError{
						field:  fmt.Sprintf("Deployments[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListDeploymentsResponseValidationError{
						field:  fmt.Sprintf("Deployments[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListDeploymentsResponseValidationError{
					field:  fmt.Sprintf("Deployments[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextPageToken

	if len(errors) > 0 {
		return ListDeploymentsResponseMultiError(errors)
	}

	return nil
}

// ListDeploymentsResponseMultiError is an error wrapping multiple validation
// errors returned by ListDeploymentsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListDeploymentsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListDeploymentsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListDeploymentsResponseMultiError) AllErrors() []error { return m }

// ListDeploymentsResponseValidationError is the validation error returned by
// ListDeploymentsResponse.Validate if the designated constraints aren't met.
type ListDeploymentsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListDeploymentsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListDeploymentsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListDeploymentsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListDeploymentsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListDeploymentsResponseValidationError) ErrorName() string {
	return "ListDeploymentsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListDeploymentsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListDeploymentsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListDeploymentsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListDeploymentsResponseValidationError{}

// Validate checks the field values on CancelDeploymentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CancelDeploymentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CancelDeploymentRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CancelDeploymentRequestMultiError, or nil if none found.
func (m *CancelDeploymentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CancelDeploymentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DeploymentId

	// no validation rules for Reason

	if len(errors) > 0 {
		return CancelDeploymentRequestMultiError(errors)
	}

	return nil
}

// CancelDeploymentRequestMultiError is an error wrapping multiple validation
// errors returned by CancelDeploymentRequest.ValidateAll() if the designated
// constraints aren't met.
type CancelDeploymentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CancelDeploymentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CancelDeploymentRequestMultiError) AllErrors() []error { return m }

// CancelDeploymentRequestValidationError is the validation error returned by
// CancelDeploymentRequest.Validate if the designated constraints aren't met.
type CancelDeploymentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CancelDeploymentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CancelDeploymentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CancelDeploymentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CancelDeploymentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CancelDeploymentRequestValidationError) ErrorName() string {
	return "CancelDeploymentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CancelDeploymentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCancelDeploymentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CancelDeploymentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CancelDeploymentRequestValidationError{}

// Validate checks the field values on CancelDeploymentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CancelDeploymentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CancelDeploymentResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CancelDeploymentResponseMultiError, or nil if none found.
func (m *CancelDeploymentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CancelDeploymentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDeployment()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CancelDeploymentResponseValidationError{
					field:  "Deployment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CancelDeploymentResponseValidationError{
					field:  "Deployment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDeployment()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CancelDeploymentResponseValidationError{
				field:  "Deployment",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CancelDeploymentResponseMultiError(errors)
	}

	return nil
}

// CancelDeploymentResponseMultiError is an error wrapping multiple validation
// errors returned by CancelDeploymentResponse.ValidateAll() if the designated
// constraints aren't met.
type CancelDeploymentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CancelDeploymentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CancelDeploymentResponseMultiError) AllErrors() []error { return m }

// CancelDeploymentResponseValidationError is the validation error returned by
// CancelDeploymentResponse.Validate if the designated constraints aren't met.
type CancelDeploymentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CancelDeploymentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CancelDeploymentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CancelDeploymentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CancelDeploymentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CancelDeploymentResponseValidationError) ErrorName() string {
	return "CancelDeploymentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CancelDeploymentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCancelDeploymentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CancelDeploymentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CancelDeploymentResponseValidationError{}

// Validate checks the field values on GetRevisionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRevisionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRevisionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRevisionRequestMultiError, or nil if none found.
func (m *GetRevisionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRevisionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DeploymentId

	// no validation rules for RevisionId

	if len(errors) > 0 {
		return GetRevisionRequestMultiError(errors)
	}

	return nil
}

// GetRevisionRequestMultiError is an error wrapping multiple validation errors
// returned by GetRevisionRequest.ValidateAll() if the designated constraints
// aren't met.
type GetRevisionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRevisionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRevisionRequestMultiError) AllErrors() []error { return m }

// GetRevisionRequestValidationError is the validation error returned by
// GetRevisionRequest.Validate if the designated constraints aren't met.
type GetRevisionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRevisionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRevisionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRevisionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRevisionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRevisionRequestValidationError) ErrorName() string {
	return "GetRevisionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetRevisionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRevisionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRevisionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRevisionRequestValidationError{}

// Validate checks the field values on GetRevisionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRevisionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRevisionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRevisionResponseMultiError, or nil if none found.
func (m *GetRevisionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRevisionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRevision()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetRevisionResponseValidationError{
					field:  "Revision",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetRevisionResponseValidationError{
					field:  "Revision",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRevision()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetRevisionResponseValidationError{
				field:  "Revision",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetRevisionResponseMultiError(errors)
	}

	return nil
}

// GetRevisionResponseMultiError is an error wrapping multiple validation
// errors returned by GetRevisionResponse.ValidateAll() if the designated
// constraints aren't met.
type GetRevisionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRevisionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRevisionResponseMultiError) AllErrors() []error { return m }

// GetRevisionResponseValidationError is the validation error returned by
// GetRevisionResponse.Validate if the designated constraints aren't met.
type GetRevisionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRevisionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRevisionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRevisionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRevisionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRevisionResponseValidationError) ErrorName() string {
	return "GetRevisionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetRevisionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRevisionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRevisionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRevisionResponseValidationError{}

// Validate checks the field values on ListRevisionsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRevisionsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRevisionsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRevisionsRequestMultiError, or nil if none found.
func (m *ListRevisionsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRevisionsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DeploymentId

	// no validation rules for PageSize

	// no validation rules for PageToken

	if len(errors) > 0 {
		return ListRevisionsRequestMultiError(errors)
	}

	return nil
}

// ListRevisionsRequestMultiError is an error wrapping multiple validation
// errors returned by ListRevisionsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListRevisionsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRevisionsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRevisionsRequestMultiError) AllErrors() []error { return m }

// ListRevisionsRequestValidationError is the validation error returned by
// ListRevisionsRequest.Validate if the designated constraints aren't met.
type ListRevisionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRevisionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRevisionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRevisionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRevisionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRevisionsRequestValidationError) ErrorName() string {
	return "ListRevisionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListRevisionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRevisionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRevisionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRevisionsRequestValidationError{}

// Validate checks the field values on ListRevisionsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRevisionsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRevisionsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRevisionsResponseMultiError, or nil if none found.
func (m *ListRevisionsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRevisionsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetRevisions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListRevisionsResponseValidationError{
						field:  fmt.Sprintf("Revisions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListRevisionsResponseValidationError{
						field:  fmt.Sprintf("Revisions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListRevisionsResponseValidationError{
					field:  fmt.Sprintf("Revisions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextPageToken

	if len(errors) > 0 {
		return ListRevisionsResponseMultiError(errors)
	}

	return nil
}

// ListRevisionsResponseMultiError is an error wrapping multiple validation
// errors returned by ListRevisionsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListRevisionsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRevisionsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRevisionsResponseMultiError) AllErrors() []error { return m }

// ListRevisionsResponseValidationError is the validation error returned by
// ListRevisionsResponse.Validate if the designated constraints aren't met.
type ListRevisionsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRevisionsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRevisionsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRevisionsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRevisionsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRevisionsResponseValidationError) ErrorName() string {
	return "ListRevisionsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListRevisionsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRevisionsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRevisionsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRevisionsResponseValidationError{}

// Validate checks the field values on RetryRevisionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RetryRevisionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RetryRevisionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RetryRevisionRequestMultiError, or nil if none found.
func (m *RetryRevisionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RetryRevisionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DeploymentId

	// no validation rules for RevisionId

	if len(errors) > 0 {
		return RetryRevisionRequestMultiError(errors)
	}

	return nil
}

// RetryRevisionRequestMultiError is an error wrapping multiple validation
// errors returned by RetryRevisionRequest.ValidateAll() if the designated
// constraints aren't met.
type RetryRevisionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RetryRevisionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RetryRevisionRequestMultiError) AllErrors() []error { return m }

// RetryRevisionRequestValidationError is the validation error returned by
// RetryRevisionRequest.Validate if the designated constraints aren't met.
type RetryRevisionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RetryRevisionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RetryRevisionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RetryRevisionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RetryRevisionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RetryRevisionRequestValidationError) ErrorName() string {
	return "RetryRevisionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RetryRevisionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRetryRevisionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RetryRevisionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RetryRevisionRequestValidationError{}

// Validate checks the field values on RetryRevisionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RetryRevisionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RetryRevisionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RetryRevisionResponseMultiError, or nil if none found.
func (m *RetryRevisionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RetryRevisionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRevision()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RetryRevisionResponseValidationError{
					field:  "Revision",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RetryRevisionResponseValidationError{
					field:  "Revision",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRevision()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RetryRevisionResponseValidationError{
				field:  "Revision",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RetryRevisionResponseMultiError(errors)
	}

	return nil
}

// RetryRevisionResponseMultiError is an error wrapping multiple validation
// errors returned by RetryRevisionResponse.ValidateAll() if the designated
// constraints aren't met.
type RetryRevisionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RetryRevisionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RetryRevisionResponseMultiError) AllErrors() []error { return m }

// RetryRevisionResponseValidationError is the validation error returned by
// RetryRevisionResponse.Validate if the designated constraints aren't met.
type RetryRevisionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RetryRevisionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RetryRevisionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RetryRevisionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RetryRevisionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RetryRevisionResponseValidationError) ErrorName() string {
	return "RetryRevisionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RetryRevisionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRetryRevisionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RetryRevisionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RetryRevisionResponseValidationError{}
