// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admiral/api/agent/v1/jobs.proto

package agentv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TerraformAgentStatus with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TerraformAgentStatus) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TerraformAgentStatus with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TerraformAgentStatusMultiError, or nil if none found.
func (m *TerraformAgentStatus) ValidateAll() error {
	return m.validate(true)
}

func (m *TerraformAgentStatus) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Version

	// no validation rules for ActiveJobs

	// no validation rules for MaxConcurrentJobs

	for idx, item := range m.GetActiveJobDetails() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TerraformAgentStatusValidationError{
						field:  fmt.Sprintf("ActiveJobDetails[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TerraformAgentStatusValidationError{
						field:  fmt.Sprintf("ActiveJobDetails[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TerraformAgentStatusValidationError{
					field:  fmt.Sprintf("ActiveJobDetails[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return TerraformAgentStatusMultiError(errors)
	}

	return nil
}

// TerraformAgentStatusMultiError is an error wrapping multiple validation
// errors returned by TerraformAgentStatus.ValidateAll() if the designated
// constraints aren't met.
type TerraformAgentStatusMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TerraformAgentStatusMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TerraformAgentStatusMultiError) AllErrors() []error { return m }

// TerraformAgentStatusValidationError is the validation error returned by
// TerraformAgentStatus.Validate if the designated constraints aren't met.
type TerraformAgentStatusValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TerraformAgentStatusValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TerraformAgentStatusValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TerraformAgentStatusValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TerraformAgentStatusValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TerraformAgentStatusValidationError) ErrorName() string {
	return "TerraformAgentStatusValidationError"
}

// Error satisfies the builtin error interface
func (e TerraformAgentStatusValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTerraformAgentStatus.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TerraformAgentStatusValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TerraformAgentStatusValidationError{}

// Validate checks the field values on ActiveJobInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ActiveJobInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ActiveJobInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ActiveJobInfoMultiError, or
// nil if none found.
func (m *ActiveJobInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *ActiveJobInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for JobId

	// no validation rules for Phase

	if all {
		switch v := interface{}(m.GetStartedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ActiveJobInfoValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ActiveJobInfoValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ActiveJobInfoValidationError{
				field:  "StartedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ActiveJobInfoMultiError(errors)
	}

	return nil
}

// ActiveJobInfoMultiError is an error wrapping multiple validation errors
// returned by ActiveJobInfo.ValidateAll() if the designated constraints
// aren't met.
type ActiveJobInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ActiveJobInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ActiveJobInfoMultiError) AllErrors() []error { return m }

// ActiveJobInfoValidationError is the validation error returned by
// ActiveJobInfo.Validate if the designated constraints aren't met.
type ActiveJobInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ActiveJobInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ActiveJobInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ActiveJobInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ActiveJobInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ActiveJobInfoValidationError) ErrorName() string { return "ActiveJobInfoValidationError" }

// Error satisfies the builtin error interface
func (e ActiveJobInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sActiveJobInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ActiveJobInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ActiveJobInfoValidationError{}

// Validate checks the field values on Job with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Job) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Job with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in JobMultiError, or nil if none found.
func (m *Job) ValidateAll() error {
	return m.validate(true)
}

func (m *Job) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for AgentId

	// no validation rules for RevisionId

	// no validation rules for RunId

	// no validation rules for JobType

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetStartedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, JobValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, JobValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return JobValidationError{
				field:  "StartedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCompletedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, JobValidationError{
					field:  "CompletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, JobValidationError{
					field:  "CompletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCompletedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return JobValidationError{
				field:  "CompletedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, JobValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, JobValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return JobValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return JobMultiError(errors)
	}

	return nil
}

// JobMultiError is an error wrapping multiple validation errors returned by
// Job.ValidateAll() if the designated constraints aren't met.
type JobMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m JobMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m JobMultiError) AllErrors() []error { return m }

// JobValidationError is the validation error returned by Job.Validate if the
// designated constraints aren't met.
type JobValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e JobValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e JobValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e JobValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e JobValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e JobValidationError) ErrorName() string { return "JobValidationError" }

// Error satisfies the builtin error interface
func (e JobValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJob.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = JobValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = JobValidationError{}

// Validate checks the field values on JobBundle with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *JobBundle) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on JobBundle with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in JobBundleMultiError, or nil
// if none found.
func (m *JobBundle) ValidateAll() error {
	return m.validate(true)
}

func (m *JobBundle) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ArtifactUrl

	// no validation rules for ArtifactChecksum

	// no validation rules for Variables

	// no validation rules for ProviderConfigs

	// no validation rules for BackendConfig

	// no validation rules for Engine

	// no validation rules for EngineVersion

	// no validation rules for WorkingDirectory

	// no validation rules for PlanFileUrl

	if all {
		switch v := interface{}(m.GetHooks()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, JobBundleValidationError{
					field:  "Hooks",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, JobBundleValidationError{
					field:  "Hooks",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetHooks()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return JobBundleValidationError{
				field:  "Hooks",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return JobBundleMultiError(errors)
	}

	return nil
}

// JobBundleMultiError is an error wrapping multiple validation errors returned
// by JobBundle.ValidateAll() if the designated constraints aren't met.
type JobBundleMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m JobBundleMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m JobBundleMultiError) AllErrors() []error { return m }

// JobBundleValidationError is the validation error returned by
// JobBundle.Validate if the designated constraints aren't met.
type JobBundleValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e JobBundleValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e JobBundleValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e JobBundleValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e JobBundleValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e JobBundleValidationError) ErrorName() string { return "JobBundleValidationError" }

// Error satisfies the builtin error interface
func (e JobBundleValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJobBundle.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = JobBundleValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = JobBundleValidationError{}

// Validate checks the field values on Hook with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Hook) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Hook with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in HookMultiError, or nil if none found.
func (m *Hook) ValidateAll() error {
	return m.validate(true)
}

func (m *Hook) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Script

	// no validation rules for TimeoutSeconds

	// no validation rules for Name

	// no validation rules for Interpreter

	if len(errors) > 0 {
		return HookMultiError(errors)
	}

	return nil
}

// HookMultiError is an error wrapping multiple validation errors returned by
// Hook.ValidateAll() if the designated constraints aren't met.
type HookMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HookMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HookMultiError) AllErrors() []error { return m }

// HookValidationError is the validation error returned by Hook.Validate if the
// designated constraints aren't met.
type HookValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HookValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HookValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HookValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HookValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HookValidationError) ErrorName() string { return "HookValidationError" }

// Error satisfies the builtin error interface
func (e HookValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHook.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HookValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HookValidationError{}

// Validate checks the field values on Hooks with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Hooks) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Hooks with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in HooksMultiError, or nil if none found.
func (m *Hooks) ValidateAll() error {
	return m.validate(true)
}

func (m *Hooks) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetBeforeInit() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HooksValidationError{
						field:  fmt.Sprintf("BeforeInit[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HooksValidationError{
						field:  fmt.Sprintf("BeforeInit[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HooksValidationError{
					field:  fmt.Sprintf("BeforeInit[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetAfterInit() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HooksValidationError{
						field:  fmt.Sprintf("AfterInit[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HooksValidationError{
						field:  fmt.Sprintf("AfterInit[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HooksValidationError{
					field:  fmt.Sprintf("AfterInit[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetBeforePlan() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HooksValidationError{
						field:  fmt.Sprintf("BeforePlan[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HooksValidationError{
						field:  fmt.Sprintf("BeforePlan[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HooksValidationError{
					field:  fmt.Sprintf("BeforePlan[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetAfterPlan() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HooksValidationError{
						field:  fmt.Sprintf("AfterPlan[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HooksValidationError{
						field:  fmt.Sprintf("AfterPlan[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HooksValidationError{
					field:  fmt.Sprintf("AfterPlan[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetBeforeApply() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HooksValidationError{
						field:  fmt.Sprintf("BeforeApply[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HooksValidationError{
						field:  fmt.Sprintf("BeforeApply[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HooksValidationError{
					field:  fmt.Sprintf("BeforeApply[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetAfterApply() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HooksValidationError{
						field:  fmt.Sprintf("AfterApply[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HooksValidationError{
						field:  fmt.Sprintf("AfterApply[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HooksValidationError{
					field:  fmt.Sprintf("AfterApply[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetAfterRun() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HooksValidationError{
						field:  fmt.Sprintf("AfterRun[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HooksValidationError{
						field:  fmt.Sprintf("AfterRun[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HooksValidationError{
					field:  fmt.Sprintf("AfterRun[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return HooksMultiError(errors)
	}

	return nil
}

// HooksMultiError is an error wrapping multiple validation errors returned by
// Hooks.ValidateAll() if the designated constraints aren't met.
type HooksMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HooksMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HooksMultiError) AllErrors() []error { return m }

// HooksValidationError is the validation error returned by Hooks.Validate if
// the designated constraints aren't met.
type HooksValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HooksValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HooksValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HooksValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HooksValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HooksValidationError) ErrorName() string { return "HooksValidationError" }

// Error satisfies the builtin error interface
func (e HooksValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHooks.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HooksValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HooksValidationError{}

// Validate checks the field values on HeartbeatRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *HeartbeatRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HeartbeatRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HeartbeatRequestMultiError, or nil if none found.
func (m *HeartbeatRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *HeartbeatRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetStatus()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, HeartbeatRequestValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, HeartbeatRequestValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStatus()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return HeartbeatRequestValidationError{
				field:  "Status",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for InstanceId

	if len(errors) > 0 {
		return HeartbeatRequestMultiError(errors)
	}

	return nil
}

// HeartbeatRequestMultiError is an error wrapping multiple validation errors
// returned by HeartbeatRequest.ValidateAll() if the designated constraints
// aren't met.
type HeartbeatRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HeartbeatRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HeartbeatRequestMultiError) AllErrors() []error { return m }

// HeartbeatRequestValidationError is the validation error returned by
// HeartbeatRequest.Validate if the designated constraints aren't met.
type HeartbeatRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HeartbeatRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HeartbeatRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HeartbeatRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HeartbeatRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HeartbeatRequestValidationError) ErrorName() string { return "HeartbeatRequestValidationError" }

// Error satisfies the builtin error interface
func (e HeartbeatRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHeartbeatRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HeartbeatRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HeartbeatRequestValidationError{}

// Validate checks the field values on HeartbeatResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *HeartbeatResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HeartbeatResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HeartbeatResponseMultiError, or nil if none found.
func (m *HeartbeatResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *HeartbeatResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Ack

	// no validation rules for NextHeartbeatSeconds

	if len(errors) > 0 {
		return HeartbeatResponseMultiError(errors)
	}

	return nil
}

// HeartbeatResponseMultiError is an error wrapping multiple validation errors
// returned by HeartbeatResponse.ValidateAll() if the designated constraints
// aren't met.
type HeartbeatResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HeartbeatResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HeartbeatResponseMultiError) AllErrors() []error { return m }

// HeartbeatResponseValidationError is the validation error returned by
// HeartbeatResponse.Validate if the designated constraints aren't met.
type HeartbeatResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HeartbeatResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HeartbeatResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HeartbeatResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HeartbeatResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HeartbeatResponseValidationError) ErrorName() string {
	return "HeartbeatResponseValidationError"
}

// Error satisfies the builtin error interface
func (e HeartbeatResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHeartbeatResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HeartbeatResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HeartbeatResponseValidationError{}

// Validate checks the field values on ClaimJobRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ClaimJobRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ClaimJobRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ClaimJobRequestMultiError, or nil if none found.
func (m *ClaimJobRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ClaimJobRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ClaimJobRequestMultiError(errors)
	}

	return nil
}

// ClaimJobRequestMultiError is an error wrapping multiple validation errors
// returned by ClaimJobRequest.ValidateAll() if the designated constraints
// aren't met.
type ClaimJobRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClaimJobRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClaimJobRequestMultiError) AllErrors() []error { return m }

// ClaimJobRequestValidationError is the validation error returned by
// ClaimJobRequest.Validate if the designated constraints aren't met.
type ClaimJobRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClaimJobRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClaimJobRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClaimJobRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClaimJobRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClaimJobRequestValidationError) ErrorName() string { return "ClaimJobRequestValidationError" }

// Error satisfies the builtin error interface
func (e ClaimJobRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClaimJobRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClaimJobRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClaimJobRequestValidationError{}

// Validate checks the field values on ClaimJobResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ClaimJobResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ClaimJobResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ClaimJobResponseMultiError, or nil if none found.
func (m *ClaimJobResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ClaimJobResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetJob()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ClaimJobResponseValidationError{
					field:  "Job",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ClaimJobResponseValidationError{
					field:  "Job",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetJob()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ClaimJobResponseValidationError{
				field:  "Job",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ClaimJobResponseMultiError(errors)
	}

	return nil
}

// ClaimJobResponseMultiError is an error wrapping multiple validation errors
// returned by ClaimJobResponse.ValidateAll() if the designated constraints
// aren't met.
type ClaimJobResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClaimJobResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClaimJobResponseMultiError) AllErrors() []error { return m }

// ClaimJobResponseValidationError is the validation error returned by
// ClaimJobResponse.Validate if the designated constraints aren't met.
type ClaimJobResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClaimJobResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClaimJobResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClaimJobResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClaimJobResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClaimJobResponseValidationError) ErrorName() string { return "ClaimJobResponseValidationError" }

// Error satisfies the builtin error interface
func (e ClaimJobResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClaimJobResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClaimJobResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClaimJobResponseValidationError{}

// Validate checks the field values on GetJobBundleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetJobBundleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetJobBundleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetJobBundleRequestMultiError, or nil if none found.
func (m *GetJobBundleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetJobBundleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for JobId

	if len(errors) > 0 {
		return GetJobBundleRequestMultiError(errors)
	}

	return nil
}

// GetJobBundleRequestMultiError is an error wrapping multiple validation
// errors returned by GetJobBundleRequest.ValidateAll() if the designated
// constraints aren't met.
type GetJobBundleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetJobBundleRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetJobBundleRequestMultiError) AllErrors() []error { return m }

// GetJobBundleRequestValidationError is the validation error returned by
// GetJobBundleRequest.Validate if the designated constraints aren't met.
type GetJobBundleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetJobBundleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetJobBundleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetJobBundleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetJobBundleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetJobBundleRequestValidationError) ErrorName() string {
	return "GetJobBundleRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetJobBundleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetJobBundleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetJobBundleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetJobBundleRequestValidationError{}

// Validate checks the field values on GetJobBundleResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetJobBundleResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetJobBundleResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetJobBundleResponseMultiError, or nil if none found.
func (m *GetJobBundleResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetJobBundleResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetBundle()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetJobBundleResponseValidationError{
					field:  "Bundle",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetJobBundleResponseValidationError{
					field:  "Bundle",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBundle()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetJobBundleResponseValidationError{
				field:  "Bundle",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetJobBundleResponseMultiError(errors)
	}

	return nil
}

// GetJobBundleResponseMultiError is an error wrapping multiple validation
// errors returned by GetJobBundleResponse.ValidateAll() if the designated
// constraints aren't met.
type GetJobBundleResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetJobBundleResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetJobBundleResponseMultiError) AllErrors() []error { return m }

// GetJobBundleResponseValidationError is the validation error returned by
// GetJobBundleResponse.Validate if the designated constraints aren't met.
type GetJobBundleResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetJobBundleResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetJobBundleResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetJobBundleResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetJobBundleResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetJobBundleResponseValidationError) ErrorName() string {
	return "GetJobBundleResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetJobBundleResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetJobBundleResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetJobBundleResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetJobBundleResponseValidationError{}

// Validate checks the field values on ReportJobResultRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReportJobResultRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReportJobResultRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReportJobResultRequestMultiError, or nil if none found.
func (m *ReportJobResultRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ReportJobResultRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for JobId

	if all {
		switch v := interface{}(m.GetResult()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReportJobResultRequestValidationError{
					field:  "Result",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReportJobResultRequestValidationError{
					field:  "Result",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetResult()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReportJobResultRequestValidationError{
				field:  "Result",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ReportJobResultRequestMultiError(errors)
	}

	return nil
}

// ReportJobResultRequestMultiError is an error wrapping multiple validation
// errors returned by ReportJobResultRequest.ValidateAll() if the designated
// constraints aren't met.
type ReportJobResultRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReportJobResultRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReportJobResultRequestMultiError) AllErrors() []error { return m }

// ReportJobResultRequestValidationError is the validation error returned by
// ReportJobResultRequest.Validate if the designated constraints aren't met.
type ReportJobResultRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReportJobResultRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReportJobResultRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReportJobResultRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReportJobResultRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReportJobResultRequestValidationError) ErrorName() string {
	return "ReportJobResultRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ReportJobResultRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReportJobResultRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReportJobResultRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReportJobResultRequestValidationError{}

// Validate checks the field values on ReportJobResultResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReportJobResultResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReportJobResultResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReportJobResultResponseMultiError, or nil if none found.
func (m *ReportJobResultResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ReportJobResultResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Ack

	if len(errors) > 0 {
		return ReportJobResultResponseMultiError(errors)
	}

	return nil
}

// ReportJobResultResponseMultiError is an error wrapping multiple validation
// errors returned by ReportJobResultResponse.ValidateAll() if the designated
// constraints aren't met.
type ReportJobResultResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReportJobResultResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReportJobResultResponseMultiError) AllErrors() []error { return m }

// ReportJobResultResponseValidationError is the validation error returned by
// ReportJobResultResponse.Validate if the designated constraints aren't met.
type ReportJobResultResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReportJobResultResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReportJobResultResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReportJobResultResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReportJobResultResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReportJobResultResponseValidationError) ErrorName() string {
	return "ReportJobResultResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ReportJobResultResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReportJobResultResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReportJobResultResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReportJobResultResponseValidationError{}

// Validate checks the field values on ListAgentJobsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListAgentJobsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAgentJobsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAgentJobsRequestMultiError, or nil if none found.
func (m *ListAgentJobsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAgentJobsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AgentId

	// no validation rules for Filter

	// no validation rules for PageSize

	// no validation rules for PageToken

	if len(errors) > 0 {
		return ListAgentJobsRequestMultiError(errors)
	}

	return nil
}

// ListAgentJobsRequestMultiError is an error wrapping multiple validation
// errors returned by ListAgentJobsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListAgentJobsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAgentJobsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAgentJobsRequestMultiError) AllErrors() []error { return m }

// ListAgentJobsRequestValidationError is the validation error returned by
// ListAgentJobsRequest.Validate if the designated constraints aren't met.
type ListAgentJobsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAgentJobsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAgentJobsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAgentJobsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAgentJobsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAgentJobsRequestValidationError) ErrorName() string {
	return "ListAgentJobsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListAgentJobsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAgentJobsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAgentJobsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAgentJobsRequestValidationError{}

// Validate checks the field values on ListAgentJobsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListAgentJobsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAgentJobsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAgentJobsResponseMultiError, or nil if none found.
func (m *ListAgentJobsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAgentJobsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetJobs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListAgentJobsResponseValidationError{
						field:  fmt.Sprintf("Jobs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListAgentJobsResponseValidationError{
						field:  fmt.Sprintf("Jobs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListAgentJobsResponseValidationError{
					field:  fmt.Sprintf("Jobs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextPageToken

	if len(errors) > 0 {
		return ListAgentJobsResponseMultiError(errors)
	}

	return nil
}

// ListAgentJobsResponseMultiError is an error wrapping multiple validation
// errors returned by ListAgentJobsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListAgentJobsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAgentJobsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAgentJobsResponseMultiError) AllErrors() []error { return m }

// ListAgentJobsResponseValidationError is the validation error returned by
// ListAgentJobsResponse.Validate if the designated constraints aren't met.
type ListAgentJobsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAgentJobsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAgentJobsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAgentJobsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAgentJobsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAgentJobsResponseValidationError) ErrorName() string {
	return "ListAgentJobsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListAgentJobsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAgentJobsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAgentJobsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAgentJobsResponseValidationError{}
