// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admiral/component/v1/component.proto

package componentv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ComponentOutput with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ComponentOutput) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ComponentOutput with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ComponentOutputMultiError, or nil if none found.
func (m *ComponentOutput) ValidateAll() error {
	return m.validate(true)
}

func (m *ComponentOutput) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for ValueTemplate

	// no validation rules for Description

	if len(errors) > 0 {
		return ComponentOutputMultiError(errors)
	}

	return nil
}

// ComponentOutputMultiError is an error wrapping multiple validation errors
// returned by ComponentOutput.ValidateAll() if the designated constraints
// aren't met.
type ComponentOutputMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ComponentOutputMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ComponentOutputMultiError) AllErrors() []error { return m }

// ComponentOutputValidationError is the validation error returned by
// ComponentOutput.Validate if the designated constraints aren't met.
type ComponentOutputValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ComponentOutputValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ComponentOutputValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ComponentOutputValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ComponentOutputValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ComponentOutputValidationError) ErrorName() string { return "ComponentOutputValidationError" }

// Error satisfies the builtin error interface
func (e ComponentOutputValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sComponentOutput.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ComponentOutputValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ComponentOutputValidationError{}

// Validate checks the field values on Component with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Component) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Component with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ComponentMultiError, or nil
// if none found.
func (m *Component) ValidateAll() error {
	return m.validate(true)
}

func (m *Component) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ApplicationId

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for Category

	// no validation rules for SourceId

	// no validation rules for Version

	// no validation rules for ValuesTemplate

	for idx, item := range m.GetOutputs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ComponentValidationError{
						field:  fmt.Sprintf("Outputs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ComponentValidationError{
						field:  fmt.Sprintf("Outputs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ComponentValidationError{
					field:  fmt.Sprintf("Outputs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Disabled

	// no validation rules for HasOverride

	if all {
		switch v := interface{}(m.GetCreatedBy()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ComponentValidationError{
					field:  "CreatedBy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ComponentValidationError{
					field:  "CreatedBy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedBy()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ComponentValidationError{
				field:  "CreatedBy",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ComponentValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ComponentValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ComponentValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ComponentValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ComponentValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ComponentValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ComponentMultiError(errors)
	}

	return nil
}

// ComponentMultiError is an error wrapping multiple validation errors returned
// by Component.ValidateAll() if the designated constraints aren't met.
type ComponentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ComponentMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ComponentMultiError) AllErrors() []error { return m }

// ComponentValidationError is the validation error returned by
// Component.Validate if the designated constraints aren't met.
type ComponentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ComponentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ComponentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ComponentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ComponentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ComponentValidationError) ErrorName() string { return "ComponentValidationError" }

// Error satisfies the builtin error interface
func (e ComponentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sComponent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ComponentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ComponentValidationError{}

// Validate checks the field values on ComponentOverride with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ComponentOverride) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ComponentOverride with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ComponentOverrideMultiError, or nil if none found.
func (m *ComponentOverride) ValidateAll() error {
	return m.validate(true)
}

func (m *ComponentOverride) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ComponentId

	// no validation rules for EnvironmentId

	// no validation rules for Disabled

	for idx, item := range m.GetOutputs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ComponentOverrideValidationError{
						field:  fmt.Sprintf("Outputs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ComponentOverrideValidationError{
						field:  fmt.Sprintf("Outputs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ComponentOverrideValidationError{
					field:  fmt.Sprintf("Outputs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetCreatedBy()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ComponentOverrideValidationError{
					field:  "CreatedBy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ComponentOverrideValidationError{
					field:  "CreatedBy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedBy()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ComponentOverrideValidationError{
				field:  "CreatedBy",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ComponentOverrideValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ComponentOverrideValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ComponentOverrideValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ComponentOverrideValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ComponentOverrideValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ComponentOverrideValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.SourceId != nil {
		// no validation rules for SourceId
	}

	if m.Version != nil {
		// no validation rules for Version
	}

	if m.ValuesTemplate != nil {
		// no validation rules for ValuesTemplate
	}

	if len(errors) > 0 {
		return ComponentOverrideMultiError(errors)
	}

	return nil
}

// ComponentOverrideMultiError is an error wrapping multiple validation errors
// returned by ComponentOverride.ValidateAll() if the designated constraints
// aren't met.
type ComponentOverrideMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ComponentOverrideMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ComponentOverrideMultiError) AllErrors() []error { return m }

// ComponentOverrideValidationError is the validation error returned by
// ComponentOverride.Validate if the designated constraints aren't met.
type ComponentOverrideValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ComponentOverrideValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ComponentOverrideValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ComponentOverrideValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ComponentOverrideValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ComponentOverrideValidationError) ErrorName() string {
	return "ComponentOverrideValidationError"
}

// Error satisfies the builtin error interface
func (e ComponentOverrideValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sComponentOverride.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ComponentOverrideValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ComponentOverrideValidationError{}

// Validate checks the field values on CreateComponentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateComponentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateComponentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateComponentRequestMultiError, or nil if none found.
func (m *CreateComponentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateComponentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ApplicationId

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for SourceId

	// no validation rules for Version

	// no validation rules for ValuesTemplate

	for idx, item := range m.GetOutputs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CreateComponentRequestValidationError{
						field:  fmt.Sprintf("Outputs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CreateComponentRequestValidationError{
						field:  fmt.Sprintf("Outputs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreateComponentRequestValidationError{
					field:  fmt.Sprintf("Outputs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return CreateComponentRequestMultiError(errors)
	}

	return nil
}

// CreateComponentRequestMultiError is an error wrapping multiple validation
// errors returned by CreateComponentRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateComponentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateComponentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateComponentRequestMultiError) AllErrors() []error { return m }

// CreateComponentRequestValidationError is the validation error returned by
// CreateComponentRequest.Validate if the designated constraints aren't met.
type CreateComponentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateComponentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateComponentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateComponentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateComponentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateComponentRequestValidationError) ErrorName() string {
	return "CreateComponentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateComponentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateComponentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateComponentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateComponentRequestValidationError{}

// Validate checks the field values on CreateComponentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateComponentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateComponentResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateComponentResponseMultiError, or nil if none found.
func (m *CreateComponentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateComponentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetComponent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateComponentResponseValidationError{
					field:  "Component",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateComponentResponseValidationError{
					field:  "Component",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetComponent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateComponentResponseValidationError{
				field:  "Component",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateComponentResponseMultiError(errors)
	}

	return nil
}

// CreateComponentResponseMultiError is an error wrapping multiple validation
// errors returned by CreateComponentResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateComponentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateComponentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateComponentResponseMultiError) AllErrors() []error { return m }

// CreateComponentResponseValidationError is the validation error returned by
// CreateComponentResponse.Validate if the designated constraints aren't met.
type CreateComponentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateComponentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateComponentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateComponentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateComponentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateComponentResponseValidationError) ErrorName() string {
	return "CreateComponentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateComponentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateComponentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateComponentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateComponentResponseValidationError{}

// Validate checks the field values on GetComponentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetComponentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetComponentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetComponentRequestMultiError, or nil if none found.
func (m *GetComponentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetComponentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ComponentId

	if len(errors) > 0 {
		return GetComponentRequestMultiError(errors)
	}

	return nil
}

// GetComponentRequestMultiError is an error wrapping multiple validation
// errors returned by GetComponentRequest.ValidateAll() if the designated
// constraints aren't met.
type GetComponentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetComponentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetComponentRequestMultiError) AllErrors() []error { return m }

// GetComponentRequestValidationError is the validation error returned by
// GetComponentRequest.Validate if the designated constraints aren't met.
type GetComponentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetComponentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetComponentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetComponentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetComponentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetComponentRequestValidationError) ErrorName() string {
	return "GetComponentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetComponentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetComponentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetComponentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetComponentRequestValidationError{}

// Validate checks the field values on GetComponentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetComponentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetComponentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetComponentResponseMultiError, or nil if none found.
func (m *GetComponentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetComponentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetComponent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetComponentResponseValidationError{
					field:  "Component",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetComponentResponseValidationError{
					field:  "Component",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetComponent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetComponentResponseValidationError{
				field:  "Component",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetComponentResponseMultiError(errors)
	}

	return nil
}

// GetComponentResponseMultiError is an error wrapping multiple validation
// errors returned by GetComponentResponse.ValidateAll() if the designated
// constraints aren't met.
type GetComponentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetComponentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetComponentResponseMultiError) AllErrors() []error { return m }

// GetComponentResponseValidationError is the validation error returned by
// GetComponentResponse.Validate if the designated constraints aren't met.
type GetComponentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetComponentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetComponentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetComponentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetComponentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetComponentResponseValidationError) ErrorName() string {
	return "GetComponentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetComponentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetComponentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetComponentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetComponentResponseValidationError{}

// Validate checks the field values on ListComponentsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListComponentsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListComponentsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListComponentsRequestMultiError, or nil if none found.
func (m *ListComponentsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListComponentsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Filter

	// no validation rules for PageSize

	// no validation rules for PageToken

	if len(errors) > 0 {
		return ListComponentsRequestMultiError(errors)
	}

	return nil
}

// ListComponentsRequestMultiError is an error wrapping multiple validation
// errors returned by ListComponentsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListComponentsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListComponentsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListComponentsRequestMultiError) AllErrors() []error { return m }

// ListComponentsRequestValidationError is the validation error returned by
// ListComponentsRequest.Validate if the designated constraints aren't met.
type ListComponentsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListComponentsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListComponentsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListComponentsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListComponentsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListComponentsRequestValidationError) ErrorName() string {
	return "ListComponentsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListComponentsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListComponentsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListComponentsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListComponentsRequestValidationError{}

// Validate checks the field values on ListComponentsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListComponentsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListComponentsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListComponentsResponseMultiError, or nil if none found.
func (m *ListComponentsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListComponentsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetComponents() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListComponentsResponseValidationError{
						field:  fmt.Sprintf("Components[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListComponentsResponseValidationError{
						field:  fmt.Sprintf("Components[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListComponentsResponseValidationError{
					field:  fmt.Sprintf("Components[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextPageToken

	if len(errors) > 0 {
		return ListComponentsResponseMultiError(errors)
	}

	return nil
}

// ListComponentsResponseMultiError is an error wrapping multiple validation
// errors returned by ListComponentsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListComponentsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListComponentsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListComponentsResponseMultiError) AllErrors() []error { return m }

// ListComponentsResponseValidationError is the validation error returned by
// ListComponentsResponse.Validate if the designated constraints aren't met.
type ListComponentsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListComponentsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListComponentsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListComponentsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListComponentsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListComponentsResponseValidationError) ErrorName() string {
	return "ListComponentsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListComponentsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListComponentsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListComponentsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListComponentsResponseValidationError{}

// Validate checks the field values on UpdateComponentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateComponentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateComponentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateComponentRequestMultiError, or nil if none found.
func (m *UpdateComponentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateComponentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetComponent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateComponentRequestValidationError{
					field:  "Component",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateComponentRequestValidationError{
					field:  "Component",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetComponent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateComponentRequestValidationError{
				field:  "Component",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdateMask()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateComponentRequestValidationError{
					field:  "UpdateMask",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateComponentRequestValidationError{
					field:  "UpdateMask",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdateMask()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateComponentRequestValidationError{
				field:  "UpdateMask",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateComponentRequestMultiError(errors)
	}

	return nil
}

// UpdateComponentRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateComponentRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateComponentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateComponentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateComponentRequestMultiError) AllErrors() []error { return m }

// UpdateComponentRequestValidationError is the validation error returned by
// UpdateComponentRequest.Validate if the designated constraints aren't met.
type UpdateComponentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateComponentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateComponentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateComponentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateComponentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateComponentRequestValidationError) ErrorName() string {
	return "UpdateComponentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateComponentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateComponentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateComponentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateComponentRequestValidationError{}

// Validate checks the field values on UpdateComponentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateComponentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateComponentResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateComponentResponseMultiError, or nil if none found.
func (m *UpdateComponentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateComponentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetComponent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateComponentResponseValidationError{
					field:  "Component",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateComponentResponseValidationError{
					field:  "Component",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetComponent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateComponentResponseValidationError{
				field:  "Component",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateComponentResponseMultiError(errors)
	}

	return nil
}

// UpdateComponentResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateComponentResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateComponentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateComponentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateComponentResponseMultiError) AllErrors() []error { return m }

// UpdateComponentResponseValidationError is the validation error returned by
// UpdateComponentResponse.Validate if the designated constraints aren't met.
type UpdateComponentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateComponentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateComponentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateComponentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateComponentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateComponentResponseValidationError) ErrorName() string {
	return "UpdateComponentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateComponentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateComponentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateComponentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateComponentResponseValidationError{}

// Validate checks the field values on DeleteComponentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteComponentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteComponentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteComponentRequestMultiError, or nil if none found.
func (m *DeleteComponentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteComponentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ComponentId

	if len(errors) > 0 {
		return DeleteComponentRequestMultiError(errors)
	}

	return nil
}

// DeleteComponentRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteComponentRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteComponentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteComponentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteComponentRequestMultiError) AllErrors() []error { return m }

// DeleteComponentRequestValidationError is the validation error returned by
// DeleteComponentRequest.Validate if the designated constraints aren't met.
type DeleteComponentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteComponentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteComponentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteComponentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteComponentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteComponentRequestValidationError) ErrorName() string {
	return "DeleteComponentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteComponentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteComponentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteComponentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteComponentRequestValidationError{}

// Validate checks the field values on DeleteComponentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteComponentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteComponentResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteComponentResponseMultiError, or nil if none found.
func (m *DeleteComponentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteComponentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteComponentResponseMultiError(errors)
	}

	return nil
}

// DeleteComponentResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteComponentResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteComponentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteComponentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteComponentResponseMultiError) AllErrors() []error { return m }

// DeleteComponentResponseValidationError is the validation error returned by
// DeleteComponentResponse.Validate if the designated constraints aren't met.
type DeleteComponentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteComponentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteComponentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteComponentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteComponentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteComponentResponseValidationError) ErrorName() string {
	return "DeleteComponentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteComponentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteComponentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteComponentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteComponentResponseValidationError{}

// Validate checks the field values on SetComponentOverrideRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SetComponentOverrideRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetComponentOverrideRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetComponentOverrideRequestMultiError, or nil if none found.
func (m *SetComponentOverrideRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SetComponentOverrideRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ComponentId

	// no validation rules for EnvironmentId

	// no validation rules for Disabled

	for idx, item := range m.GetOutputs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SetComponentOverrideRequestValidationError{
						field:  fmt.Sprintf("Outputs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SetComponentOverrideRequestValidationError{
						field:  fmt.Sprintf("Outputs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SetComponentOverrideRequestValidationError{
					field:  fmt.Sprintf("Outputs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.SourceId != nil {
		// no validation rules for SourceId
	}

	if m.Version != nil {
		// no validation rules for Version
	}

	if m.ValuesTemplate != nil {
		// no validation rules for ValuesTemplate
	}

	if len(errors) > 0 {
		return SetComponentOverrideRequestMultiError(errors)
	}

	return nil
}

// SetComponentOverrideRequestMultiError is an error wrapping multiple
// validation errors returned by SetComponentOverrideRequest.ValidateAll() if
// the designated constraints aren't met.
type SetComponentOverrideRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetComponentOverrideRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetComponentOverrideRequestMultiError) AllErrors() []error { return m }

// SetComponentOverrideRequestValidationError is the validation error returned
// by SetComponentOverrideRequest.Validate if the designated constraints
// aren't met.
type SetComponentOverrideRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetComponentOverrideRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetComponentOverrideRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetComponentOverrideRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetComponentOverrideRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetComponentOverrideRequestValidationError) ErrorName() string {
	return "SetComponentOverrideRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SetComponentOverrideRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetComponentOverrideRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetComponentOverrideRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetComponentOverrideRequestValidationError{}

// Validate checks the field values on SetComponentOverrideResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SetComponentOverrideResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetComponentOverrideResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetComponentOverrideResponseMultiError, or nil if none found.
func (m *SetComponentOverrideResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SetComponentOverrideResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetOverride()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SetComponentOverrideResponseValidationError{
					field:  "Override",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SetComponentOverrideResponseValidationError{
					field:  "Override",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOverride()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SetComponentOverrideResponseValidationError{
				field:  "Override",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SetComponentOverrideResponseMultiError(errors)
	}

	return nil
}

// SetComponentOverrideResponseMultiError is an error wrapping multiple
// validation errors returned by SetComponentOverrideResponse.ValidateAll() if
// the designated constraints aren't met.
type SetComponentOverrideResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetComponentOverrideResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetComponentOverrideResponseMultiError) AllErrors() []error { return m }

// SetComponentOverrideResponseValidationError is the validation error returned
// by SetComponentOverrideResponse.Validate if the designated constraints
// aren't met.
type SetComponentOverrideResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetComponentOverrideResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetComponentOverrideResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetComponentOverrideResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetComponentOverrideResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetComponentOverrideResponseValidationError) ErrorName() string {
	return "SetComponentOverrideResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SetComponentOverrideResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetComponentOverrideResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetComponentOverrideResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetComponentOverrideResponseValidationError{}

// Validate checks the field values on GetComponentOverrideRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetComponentOverrideRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetComponentOverrideRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetComponentOverrideRequestMultiError, or nil if none found.
func (m *GetComponentOverrideRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetComponentOverrideRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ComponentId

	// no validation rules for EnvironmentId

	if len(errors) > 0 {
		return GetComponentOverrideRequestMultiError(errors)
	}

	return nil
}

// GetComponentOverrideRequestMultiError is an error wrapping multiple
// validation errors returned by GetComponentOverrideRequest.ValidateAll() if
// the designated constraints aren't met.
type GetComponentOverrideRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetComponentOverrideRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetComponentOverrideRequestMultiError) AllErrors() []error { return m }

// GetComponentOverrideRequestValidationError is the validation error returned
// by GetComponentOverrideRequest.Validate if the designated constraints
// aren't met.
type GetComponentOverrideRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetComponentOverrideRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetComponentOverrideRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetComponentOverrideRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetComponentOverrideRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetComponentOverrideRequestValidationError) ErrorName() string {
	return "GetComponentOverrideRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetComponentOverrideRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetComponentOverrideRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetComponentOverrideRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetComponentOverrideRequestValidationError{}

// Validate checks the field values on GetComponentOverrideResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetComponentOverrideResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetComponentOverrideResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetComponentOverrideResponseMultiError, or nil if none found.
func (m *GetComponentOverrideResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetComponentOverrideResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetOverride()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetComponentOverrideResponseValidationError{
					field:  "Override",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetComponentOverrideResponseValidationError{
					field:  "Override",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOverride()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetComponentOverrideResponseValidationError{
				field:  "Override",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetComponentOverrideResponseMultiError(errors)
	}

	return nil
}

// GetComponentOverrideResponseMultiError is an error wrapping multiple
// validation errors returned by GetComponentOverrideResponse.ValidateAll() if
// the designated constraints aren't met.
type GetComponentOverrideResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetComponentOverrideResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetComponentOverrideResponseMultiError) AllErrors() []error { return m }

// GetComponentOverrideResponseValidationError is the validation error returned
// by GetComponentOverrideResponse.Validate if the designated constraints
// aren't met.
type GetComponentOverrideResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetComponentOverrideResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetComponentOverrideResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetComponentOverrideResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetComponentOverrideResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetComponentOverrideResponseValidationError) ErrorName() string {
	return "GetComponentOverrideResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetComponentOverrideResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetComponentOverrideResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetComponentOverrideResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetComponentOverrideResponseValidationError{}

// Validate checks the field values on ListComponentOverridesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListComponentOverridesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListComponentOverridesRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListComponentOverridesRequestMultiError, or nil if none found.
func (m *ListComponentOverridesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListComponentOverridesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ComponentId

	// no validation rules for PageSize

	// no validation rules for PageToken

	if len(errors) > 0 {
		return ListComponentOverridesRequestMultiError(errors)
	}

	return nil
}

// ListComponentOverridesRequestMultiError is an error wrapping multiple
// validation errors returned by ListComponentOverridesRequest.ValidateAll()
// if the designated constraints aren't met.
type ListComponentOverridesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListComponentOverridesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListComponentOverridesRequestMultiError) AllErrors() []error { return m }

// ListComponentOverridesRequestValidationError is the validation error
// returned by ListComponentOverridesRequest.Validate if the designated
// constraints aren't met.
type ListComponentOverridesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListComponentOverridesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListComponentOverridesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListComponentOverridesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListComponentOverridesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListComponentOverridesRequestValidationError) ErrorName() string {
	return "ListComponentOverridesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListComponentOverridesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListComponentOverridesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListComponentOverridesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListComponentOverridesRequestValidationError{}

// Validate checks the field values on ListComponentOverridesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListComponentOverridesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListComponentOverridesResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListComponentOverridesResponseMultiError, or nil if none found.
func (m *ListComponentOverridesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListComponentOverridesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetOverrides() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListComponentOverridesResponseValidationError{
						field:  fmt.Sprintf("Overrides[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListComponentOverridesResponseValidationError{
						field:  fmt.Sprintf("Overrides[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListComponentOverridesResponseValidationError{
					field:  fmt.Sprintf("Overrides[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextPageToken

	if len(errors) > 0 {
		return ListComponentOverridesResponseMultiError(errors)
	}

	return nil
}

// ListComponentOverridesResponseMultiError is an error wrapping multiple
// validation errors returned by ListComponentOverridesResponse.ValidateAll()
// if the designated constraints aren't met.
type ListComponentOverridesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListComponentOverridesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListComponentOverridesResponseMultiError) AllErrors() []error { return m }

// ListComponentOverridesResponseValidationError is the validation error
// returned by ListComponentOverridesResponse.Validate if the designated
// constraints aren't met.
type ListComponentOverridesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListComponentOverridesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListComponentOverridesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListComponentOverridesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListComponentOverridesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListComponentOverridesResponseValidationError) ErrorName() string {
	return "ListComponentOverridesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListComponentOverridesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListComponentOverridesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListComponentOverridesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListComponentOverridesResponseValidationError{}

// Validate checks the field values on DeleteComponentOverrideRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteComponentOverrideRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteComponentOverrideRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// DeleteComponentOverrideRequestMultiError, or nil if none found.
func (m *DeleteComponentOverrideRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteComponentOverrideRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ComponentId

	// no validation rules for EnvironmentId

	if len(errors) > 0 {
		return DeleteComponentOverrideRequestMultiError(errors)
	}

	return nil
}

// DeleteComponentOverrideRequestMultiError is an error wrapping multiple
// validation errors returned by DeleteComponentOverrideRequest.ValidateAll()
// if the designated constraints aren't met.
type DeleteComponentOverrideRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteComponentOverrideRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteComponentOverrideRequestMultiError) AllErrors() []error { return m }

// DeleteComponentOverrideRequestValidationError is the validation error
// returned by DeleteComponentOverrideRequest.Validate if the designated
// constraints aren't met.
type DeleteComponentOverrideRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteComponentOverrideRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteComponentOverrideRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteComponentOverrideRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteComponentOverrideRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteComponentOverrideRequestValidationError) ErrorName() string {
	return "DeleteComponentOverrideRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteComponentOverrideRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteComponentOverrideRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteComponentOverrideRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteComponentOverrideRequestValidationError{}

// Validate checks the field values on DeleteComponentOverrideResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteComponentOverrideResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteComponentOverrideResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// DeleteComponentOverrideResponseMultiError, or nil if none found.
func (m *DeleteComponentOverrideResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteComponentOverrideResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteComponentOverrideResponseMultiError(errors)
	}

	return nil
}

// DeleteComponentOverrideResponseMultiError is an error wrapping multiple
// validation errors returned by DeleteComponentOverrideResponse.ValidateAll()
// if the designated constraints aren't met.
type DeleteComponentOverrideResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteComponentOverrideResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteComponentOverrideResponseMultiError) AllErrors() []error { return m }

// DeleteComponentOverrideResponseValidationError is the validation error
// returned by DeleteComponentOverrideResponse.Validate if the designated
// constraints aren't met.
type DeleteComponentOverrideResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteComponentOverrideResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteComponentOverrideResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteComponentOverrideResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteComponentOverrideResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteComponentOverrideResponseValidationError) ErrorName() string {
	return "DeleteComponentOverrideResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteComponentOverrideResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteComponentOverrideResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteComponentOverrideResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteComponentOverrideResponseValidationError{}
