// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: admiral/api/changeset/v1/changeset.proto

package changesetv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChangeSetAPI_CreateChangeSet_FullMethodName    = "/admiral.api.changeset.v1.ChangeSetAPI/CreateChangeSet"
	ChangeSetAPI_EditChangeSet_FullMethodName      = "/admiral.api.changeset.v1.ChangeSetAPI/EditChangeSet"
	ChangeSetAPI_GetChangeSet_FullMethodName       = "/admiral.api.changeset.v1.ChangeSetAPI/GetChangeSet"
	ChangeSetAPI_ListChangeSets_FullMethodName     = "/admiral.api.changeset.v1.ChangeSetAPI/ListChangeSets"
	ChangeSetAPI_DiscardChangeSet_FullMethodName   = "/admiral.api.changeset.v1.ChangeSetAPI/DiscardChangeSet"
	ChangeSetAPI_GetComponentValues_FullMethodName = "/admiral.api.changeset.v1.ChangeSetAPI/GetComponentValues"
	ChangeSetAPI_DiffChangeSet_FullMethodName      = "/admiral.api.changeset.v1.ChangeSetAPI/DiffChangeSet"
	ChangeSetAPI_GetRevision_FullMethodName        = "/admiral.api.changeset.v1.ChangeSetAPI/GetRevision"
	ChangeSetAPI_ListRevisions_FullMethodName      = "/admiral.api.changeset.v1.ChangeSetAPI/ListRevisions"
	ChangeSetAPI_PlanChangeSet_FullMethodName      = "/admiral.api.changeset.v1.ChangeSetAPI/PlanChangeSet"
	ChangeSetAPI_GetPrepare_FullMethodName         = "/admiral.api.changeset.v1.ChangeSetAPI/GetPrepare"
	ChangeSetAPI_GetArtifact_FullMethodName        = "/admiral.api.changeset.v1.ChangeSetAPI/GetArtifact"
)

// ChangeSetAPIClient is the client API for ChangeSetAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChangeSetAPI manages change sets: proposals against the components of one
// environment. Add a component from the registry, move its pin, set or
// remove values, remove it; each request cuts one immutable revision.
// Nothing here plans or applies.
//
// A change set is addressed by its id, `cs-` and twelve base36 characters.
//
// Values are JSON text in `*_json` fields, so an integer above 2^53 keeps
// every digit. A map whose only key is `$ref` is a reference to another
// component's output (`{"$ref": "users-db.connection_name"}`); a real value
// of that shape is written with `$$ref`.
type ChangeSetAPIClient interface {
	// CreateChangeSet opens a draft against an environment. Edits given here
	// cut revision 1 in the same request; with none, the draft has no revision
	// until its first edit.
	//
	// Scope: `changeset:write`
	CreateChangeSet(ctx context.Context, in *CreateChangeSetRequest, opts ...grpc.CallOption) (*CreateChangeSetResponse, error)
	// EditChangeSet applies the edits in order and cuts exactly one revision.
	//
	// FAILED_PRECONDITION when `if_revision` or an upload's `from_revision` is
	// not the head (the message names the head), when the change set is not a
	// draft, and when a pin names a revoked revision (the message carries the
	// recorded reason). ALREADY_EXISTS when a component name is live or held
	// by another draft (the message names which). A contract violation is
	// accepted: it is stored on the revision and returned.
	//
	// Scope: `changeset:write`
	EditChangeSet(ctx context.Context, in *EditChangeSetRequest, opts ...grpc.CallOption) (*EditChangeSetResponse, error)
	// GetChangeSet returns a change set and its head revision with entries.
	//
	// Scope: `changeset:read`
	GetChangeSet(ctx context.Context, in *GetChangeSetRequest, opts ...grpc.CallOption) (*GetChangeSetResponse, error)
	// ListChangeSets pages through one environment's change sets, oldest
	// first.
	//
	// Scope: `changeset:read`
	ListChangeSets(ctx context.Context, in *ListChangeSetsRequest, opts ...grpc.CallOption) (*ListChangeSetsResponse, error)
	// DiscardChangeSet abandons a draft and releases the component names it
	// reserved. FAILED_PRECONDITION when it is already discarded.
	//
	// Scope: `changeset:write`
	DiscardChangeSet(ctx context.Context, in *DiscardChangeSetRequest, opts ...grpc.CallOption) (*DiscardChangeSetResponse, error)
	// GetComponentValues returns one component's values as the head revision
	// leaves them, with the head's number, which an upload sends back as
	// `from_revision`.
	//
	// Scope: `changeset:read`
	GetComponentValues(ctx context.Context, in *GetComponentValuesRequest, opts ...grpc.CallOption) (*GetComponentValuesResponse, error)
	// DiffChangeSet returns, per component the head revision touches, the
	// action, the pin before and after, each changed path before and after,
	// and the component's violations.
	//
	// Scope: `changeset:read`
	DiffChangeSet(ctx context.Context, in *DiffChangeSetRequest, opts ...grpc.CallOption) (*DiffChangeSetResponse, error)
	// GetRevision returns one revision with its entries and ops.
	//
	// Scope: `changeset:read`
	GetRevision(ctx context.Context, in *GetRevisionRequest, opts ...grpc.CallOption) (*GetRevisionResponse, error)
	// ListRevisions pages through a change set's revisions, oldest first,
	// without their entries.
	//
	// Scope: `changeset:read`
	ListRevisions(ctx context.Context, in *ListRevisionsRequest, opts ...grpc.CallOption) (*ListRevisionsResponse, error)
	// PlanChangeSet asks for a plan of the head revision. The revision is
	// prepared first: every component it touches is rendered into one
	// content-addressed run artifact. The call queues that work and returns
	// at once; GetPrepare reports its progress. Asking again for a revision
	// already asked for returns the same prepare, except that a prepare which
	// failed for an infrastructure reason is queued again.
	//
	// FAILED_PRECONDITION when the change set is not a draft, has no revision,
	// or `if_revision` is not the head (the message names the head).
	//
	// Scope: `changeset:write`
	PlanChangeSet(ctx context.Context, in *PlanChangeSetRequest, opts ...grpc.CallOption) (*PlanChangeSetResponse, error)
	// GetPrepare returns the prepare of one revision: its status, findings,
	// error and artifact digest. NOT_FOUND when that revision was never
	// prepared.
	//
	// Scope: `changeset:read`
	GetPrepare(ctx context.Context, in *GetPrepareRequest, opts ...grpc.CallOption) (*GetPrepareResponse, error)
	// GetArtifact returns a prepared revision's run artifact. Every value
	// under a Secret's `data` and `stringData` is replaced by `sha256:` and
	// the first twelve hex characters of its digest, so a change stays
	// visible and the value does not. FAILED_PRECONDITION when the revision
	// is not prepared.
	//
	// Scope: `changeset:read`
	GetArtifact(ctx context.Context, in *GetArtifactRequest, opts ...grpc.CallOption) (*GetArtifactResponse, error)
}

type changeSetAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewChangeSetAPIClient(cc grpc.ClientConnInterface) ChangeSetAPIClient {
	return &changeSetAPIClient{cc}
}

func (c *changeSetAPIClient) CreateChangeSet(ctx context.Context, in *CreateChangeSetRequest, opts ...grpc.CallOption) (*CreateChangeSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateChangeSetResponse)
	err := c.cc.Invoke(ctx, ChangeSetAPI_CreateChangeSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeSetAPIClient) EditChangeSet(ctx context.Context, in *EditChangeSetRequest, opts ...grpc.CallOption) (*EditChangeSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditChangeSetResponse)
	err := c.cc.Invoke(ctx, ChangeSetAPI_EditChangeSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeSetAPIClient) GetChangeSet(ctx context.Context, in *GetChangeSetRequest, opts ...grpc.CallOption) (*GetChangeSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChangeSetResponse)
	err := c.cc.Invoke(ctx, ChangeSetAPI_GetChangeSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeSetAPIClient) ListChangeSets(ctx context.Context, in *ListChangeSetsRequest, opts ...grpc.CallOption) (*ListChangeSetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChangeSetsResponse)
	err := c.cc.Invoke(ctx, ChangeSetAPI_ListChangeSets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeSetAPIClient) DiscardChangeSet(ctx context.Context, in *DiscardChangeSetRequest, opts ...grpc.CallOption) (*DiscardChangeSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscardChangeSetResponse)
	err := c.cc.Invoke(ctx, ChangeSetAPI_DiscardChangeSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeSetAPIClient) GetComponentValues(ctx context.Context, in *GetComponentValuesRequest, opts ...grpc.CallOption) (*GetComponentValuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetComponentValuesResponse)
	err := c.cc.Invoke(ctx, ChangeSetAPI_GetComponentValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeSetAPIClient) DiffChangeSet(ctx context.Context, in *DiffChangeSetRequest, opts ...grpc.CallOption) (*DiffChangeSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiffChangeSetResponse)
	err := c.cc.Invoke(ctx, ChangeSetAPI_DiffChangeSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeSetAPIClient) GetRevision(ctx context.Context, in *GetRevisionRequest, opts ...grpc.CallOption) (*GetRevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRevisionResponse)
	err := c.cc.Invoke(ctx, ChangeSetAPI_GetRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeSetAPIClient) ListRevisions(ctx context.Context, in *ListRevisionsRequest, opts ...grpc.CallOption) (*ListRevisionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRevisionsResponse)
	err := c.cc.Invoke(ctx, ChangeSetAPI_ListRevisions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeSetAPIClient) PlanChangeSet(ctx context.Context, in *PlanChangeSetRequest, opts ...grpc.CallOption) (*PlanChangeSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanChangeSetResponse)
	err := c.cc.Invoke(ctx, ChangeSetAPI_PlanChangeSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeSetAPIClient) GetPrepare(ctx context.Context, in *GetPrepareRequest, opts ...grpc.CallOption) (*GetPrepareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrepareResponse)
	err := c.cc.Invoke(ctx, ChangeSetAPI_GetPrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeSetAPIClient) GetArtifact(ctx context.Context, in *GetArtifactRequest, opts ...grpc.CallOption) (*GetArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArtifactResponse)
	err := c.cc.Invoke(ctx, ChangeSetAPI_GetArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChangeSetAPIServer is the server API for ChangeSetAPI service.
// All implementations should embed UnimplementedChangeSetAPIServer
// for forward compatibility.
//
// ChangeSetAPI manages change sets: proposals against the components of one
// environment. Add a component from the registry, move its pin, set or
// remove values, remove it; each request cuts one immutable revision.
// Nothing here plans or applies.
//
// A change set is addressed by its id, `cs-` and twelve base36 characters.
//
// Values are JSON text in `*_json` fields, so an integer above 2^53 keeps
// every digit. A map whose only key is `$ref` is a reference to another
// component's output (`{"$ref": "users-db.connection_name"}`); a real value
// of that shape is written with `$$ref`.
type ChangeSetAPIServer interface {
	// CreateChangeSet opens a draft against an environment. Edits given here
	// cut revision 1 in the same request; with none, the draft has no revision
	// until its first edit.
	//
	// Scope: `changeset:write`
	CreateChangeSet(context.Context, *CreateChangeSetRequest) (*CreateChangeSetResponse, error)
	// EditChangeSet applies the edits in order and cuts exactly one revision.
	//
	// FAILED_PRECONDITION when `if_revision` or an upload's `from_revision` is
	// not the head (the message names the head), when the change set is not a
	// draft, and when a pin names a revoked revision (the message carries the
	// recorded reason). ALREADY_EXISTS when a component name is live or held
	// by another draft (the message names which). A contract violation is
	// accepted: it is stored on the revision and returned.
	//
	// Scope: `changeset:write`
	EditChangeSet(context.Context, *EditChangeSetRequest) (*EditChangeSetResponse, error)
	// GetChangeSet returns a change set and its head revision with entries.
	//
	// Scope: `changeset:read`
	GetChangeSet(context.Context, *GetChangeSetRequest) (*GetChangeSetResponse, error)
	// ListChangeSets pages through one environment's change sets, oldest
	// first.
	//
	// Scope: `changeset:read`
	ListChangeSets(context.Context, *ListChangeSetsRequest) (*ListChangeSetsResponse, error)
	// DiscardChangeSet abandons a draft and releases the component names it
	// reserved. FAILED_PRECONDITION when it is already discarded.
	//
	// Scope: `changeset:write`
	DiscardChangeSet(context.Context, *DiscardChangeSetRequest) (*DiscardChangeSetResponse, error)
	// GetComponentValues returns one component's values as the head revision
	// leaves them, with the head's number, which an upload sends back as
	// `from_revision`.
	//
	// Scope: `changeset:read`
	GetComponentValues(context.Context, *GetComponentValuesRequest) (*GetComponentValuesResponse, error)
	// DiffChangeSet returns, per component the head revision touches, the
	// action, the pin before and after, each changed path before and after,
	// and the component's violations.
	//
	// Scope: `changeset:read`
	DiffChangeSet(context.Context, *DiffChangeSetRequest) (*DiffChangeSetResponse, error)
	// GetRevision returns one revision with its entries and ops.
	//
	// Scope: `changeset:read`
	GetRevision(context.Context, *GetRevisionRequest) (*GetRevisionResponse, error)
	// ListRevisions pages through a change set's revisions, oldest first,
	// without their entries.
	//
	// Scope: `changeset:read`
	ListRevisions(context.Context, *ListRevisionsRequest) (*ListRevisionsResponse, error)
	// PlanChangeSet asks for a plan of the head revision. The revision is
	// prepared first: every component it touches is rendered into one
	// content-addressed run artifact. The call queues that work and returns
	// at once; GetPrepare reports its progress. Asking again for a revision
	// already asked for returns the same prepare, except that a prepare which
	// failed for an infrastructure reason is queued again.
	//
	// FAILED_PRECONDITION when the change set is not a draft, has no revision,
	// or `if_revision` is not the head (the message names the head).
	//
	// Scope: `changeset:write`
	PlanChangeSet(context.Context, *PlanChangeSetRequest) (*PlanChangeSetResponse, error)
	// GetPrepare returns the prepare of one revision: its status, findings,
	// error and artifact digest. NOT_FOUND when that revision was never
	// prepared.
	//
	// Scope: `changeset:read`
	GetPrepare(context.Context, *GetPrepareRequest) (*GetPrepareResponse, error)
	// GetArtifact returns a prepared revision's run artifact. Every value
	// under a Secret's `data` and `stringData` is replaced by `sha256:` and
	// the first twelve hex characters of its digest, so a change stays
	// visible and the value does not. FAILED_PRECONDITION when the revision
	// is not prepared.
	//
	// Scope: `changeset:read`
	GetArtifact(context.Context, *GetArtifactRequest) (*GetArtifactResponse, error)
}

// UnimplementedChangeSetAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChangeSetAPIServer struct{}

func (UnimplementedChangeSetAPIServer) CreateChangeSet(context.Context, *CreateChangeSetRequest) (*CreateChangeSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChangeSet not implemented")
}
func (UnimplementedChangeSetAPIServer) EditChangeSet(context.Context, *EditChangeSetRequest) (*EditChangeSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditChangeSet not implemented")
}
func (UnimplementedChangeSetAPIServer) GetChangeSet(context.Context, *GetChangeSetRequest) (*GetChangeSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChangeSet not implemented")
}
func (UnimplementedChangeSetAPIServer) ListChangeSets(context.Context, *ListChangeSetsRequest) (*ListChangeSetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChangeSets not implemented")
}
func (UnimplementedChangeSetAPIServer) DiscardChangeSet(context.Context, *DiscardChangeSetRequest) (*DiscardChangeSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscardChangeSet not implemented")
}
func (UnimplementedChangeSetAPIServer) GetComponentValues(context.Context, *GetComponentValuesRequest) (*GetComponentValuesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetComponentValues not implemented")
}
func (UnimplementedChangeSetAPIServer) DiffChangeSet(context.Context, *DiffChangeSetRequest) (*DiffChangeSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiffChangeSet not implemented")
}
func (UnimplementedChangeSetAPIServer) GetRevision(context.Context, *GetRevisionRequest) (*GetRevisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRevision not implemented")
}
func (UnimplementedChangeSetAPIServer) ListRevisions(context.Context, *ListRevisionsRequest) (*ListRevisionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRevisions not implemented")
}
func (UnimplementedChangeSetAPIServer) PlanChangeSet(context.Context, *PlanChangeSetRequest) (*PlanChangeSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlanChangeSet not implemented")
}
func (UnimplementedChangeSetAPIServer) GetPrepare(context.Context, *GetPrepareRequest) (*GetPrepareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrepare not implemented")
}
func (UnimplementedChangeSetAPIServer) GetArtifact(context.Context, *GetArtifactRequest) (*GetArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtifact not implemented")
}
func (UnimplementedChangeSetAPIServer) testEmbeddedByValue() {}

// UnsafeChangeSetAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChangeSetAPIServer will
// result in compilation errors.
type UnsafeChangeSetAPIServer interface {
	mustEmbedUnimplementedChangeSetAPIServer()
}

func RegisterChangeSetAPIServer(s grpc.ServiceRegistrar, srv ChangeSetAPIServer) {
	// If the following call panics, it indicates UnimplementedChangeSetAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChangeSetAPI_ServiceDesc, srv)
}

func _ChangeSetAPI_CreateChangeSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChangeSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeSetAPIServer).CreateChangeSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeSetAPI_CreateChangeSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeSetAPIServer).CreateChangeSet(ctx, req.(*CreateChangeSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeSetAPI_EditChangeSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditChangeSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeSetAPIServer).EditChangeSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeSetAPI_EditChangeSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeSetAPIServer).EditChangeSet(ctx, req.(*EditChangeSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeSetAPI_GetChangeSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChangeSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeSetAPIServer).GetChangeSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeSetAPI_GetChangeSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeSetAPIServer).GetChangeSet(ctx, req.(*GetChangeSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeSetAPI_ListChangeSets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChangeSetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeSetAPIServer).ListChangeSets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeSetAPI_ListChangeSets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeSetAPIServer).ListChangeSets(ctx, req.(*ListChangeSetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeSetAPI_DiscardChangeSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscardChangeSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeSetAPIServer).DiscardChangeSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeSetAPI_DiscardChangeSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeSetAPIServer).DiscardChangeSet(ctx, req.(*DiscardChangeSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeSetAPI_GetComponentValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComponentValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeSetAPIServer).GetComponentValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeSetAPI_GetComponentValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeSetAPIServer).GetComponentValues(ctx, req.(*GetComponentValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeSetAPI_DiffChangeSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffChangeSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeSetAPIServer).DiffChangeSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeSetAPI_DiffChangeSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeSetAPIServer).DiffChangeSet(ctx, req.(*DiffChangeSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeSetAPI_GetRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeSetAPIServer).GetRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeSetAPI_GetRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeSetAPIServer).GetRevision(ctx, req.(*GetRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeSetAPI_ListRevisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRevisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeSetAPIServer).ListRevisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeSetAPI_ListRevisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeSetAPIServer).ListRevisions(ctx, req.(*ListRevisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeSetAPI_PlanChangeSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanChangeSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeSetAPIServer).PlanChangeSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeSetAPI_PlanChangeSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeSetAPIServer).PlanChangeSet(ctx, req.(*PlanChangeSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeSetAPI_GetPrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeSetAPIServer).GetPrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeSetAPI_GetPrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeSetAPIServer).GetPrepare(ctx, req.(*GetPrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeSetAPI_GetArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeSetAPIServer).GetArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeSetAPI_GetArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeSetAPIServer).GetArtifact(ctx, req.(*GetArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChangeSetAPI_ServiceDesc is the grpc.ServiceDesc for ChangeSetAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChangeSetAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admiral.api.changeset.v1.ChangeSetAPI",
	HandlerType: (*ChangeSetAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChangeSet",
			Handler:    _ChangeSetAPI_CreateChangeSet_Handler,
		},
		{
			MethodName: "EditChangeSet",
			Handler:    _ChangeSetAPI_EditChangeSet_Handler,
		},
		{
			MethodName: "GetChangeSet",
			Handler:    _ChangeSetAPI_GetChangeSet_Handler,
		},
		{
			MethodName: "ListChangeSets",
			Handler:    _ChangeSetAPI_ListChangeSets_Handler,
		},
		{
			MethodName: "DiscardChangeSet",
			Handler:    _ChangeSetAPI_DiscardChangeSet_Handler,
		},
		{
			MethodName: "GetComponentValues",
			Handler:    _ChangeSetAPI_GetComponentValues_Handler,
		},
		{
			MethodName: "DiffChangeSet",
			Handler:    _ChangeSetAPI_DiffChangeSet_Handler,
		},
		{
			MethodName: "GetRevision",
			Handler:    _ChangeSetAPI_GetRevision_Handler,
		},
		{
			MethodName: "ListRevisions",
			Handler:    _ChangeSetAPI_ListRevisions_Handler,
		},
		{
			MethodName: "PlanChangeSet",
			Handler:    _ChangeSetAPI_PlanChangeSet_Handler,
		},
		{
			MethodName: "GetPrepare",
			Handler:    _ChangeSetAPI_GetPrepare_Handler,
		},
		{
			MethodName: "GetArtifact",
			Handler:    _ChangeSetAPI_GetArtifact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admiral/api/changeset/v1/changeset.proto",
}
