// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: admiral/api/state/v1/state.proto

package statev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "go.admiral.io/sdk/proto/admiral/api/state/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// StateAPIName is the fully-qualified name of the StateAPI service.
	StateAPIName = "admiral.api.state.v1.StateAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StateAPIGetStateProcedure is the fully-qualified name of the StateAPI's GetState RPC.
	StateAPIGetStateProcedure = "/admiral.api.state.v1.StateAPI/GetState"
	// StateAPIPushStateProcedure is the fully-qualified name of the StateAPI's PushState RPC.
	StateAPIPushStateProcedure = "/admiral.api.state.v1.StateAPI/PushState"
	// StateAPILockStateProcedure is the fully-qualified name of the StateAPI's LockState RPC.
	StateAPILockStateProcedure = "/admiral.api.state.v1.StateAPI/LockState"
	// StateAPIUnlockStateProcedure is the fully-qualified name of the StateAPI's UnlockState RPC.
	StateAPIUnlockStateProcedure = "/admiral.api.state.v1.StateAPI/UnlockState"
	// StateAPIGetCurrentStateProcedure is the fully-qualified name of the StateAPI's GetCurrentState
	// RPC.
	StateAPIGetCurrentStateProcedure = "/admiral.api.state.v1.StateAPI/GetCurrentState"
	// StateAPIListStatesProcedure is the fully-qualified name of the StateAPI's ListStates RPC.
	StateAPIListStatesProcedure = "/admiral.api.state.v1.StateAPI/ListStates"
	// StateAPIListStateVersionsProcedure is the fully-qualified name of the StateAPI's
	// ListStateVersions RPC.
	StateAPIListStateVersionsProcedure = "/admiral.api.state.v1.StateAPI/ListStateVersions"
	// StateAPIGetStateVersionProcedure is the fully-qualified name of the StateAPI's GetStateVersion
	// RPC.
	StateAPIGetStateVersionProcedure = "/admiral.api.state.v1.StateAPI/GetStateVersion"
	// StateAPIForceUnlockStateProcedure is the fully-qualified name of the StateAPI's ForceUnlockState
	// RPC.
	StateAPIForceUnlockStateProcedure = "/admiral.api.state.v1.StateAPI/ForceUnlockState"
	// StateAPIDeleteStateProcedure is the fully-qualified name of the StateAPI's DeleteState RPC.
	StateAPIDeleteStateProcedure = "/admiral.api.state.v1.StateAPI/DeleteState"
)

// StateAPIClient is a client for the admiral.api.state.v1.StateAPI service.
type StateAPIClient interface {
	// GetState fetches the current state for a job's component + environment.
	// Returns empty data if no state exists yet (fresh init -- Terraform
	// handles this gracefully).
	//
	// The server validates that the AGT's runner binding matches the runner
	// assigned to this job. Returns PERMISSION_DENIED if they do not match.
	// Returns NOT_FOUND if the job does not exist or has been cancelled.
	//
	// Maps to Terraform HTTP backend GET on the state address.
	//
	// Scope: `state:read` | Token types: `agt`
	GetState(context.Context, *connect.Request[v1.GetStateRequest]) (*connect.Response[v1.GetStateResponse], error)
	// PushState stores a new state version after a successful apply. The server
	// validates the serial number (must be greater than current) and lineage
	// (must match if state already exists). Creates the state record on first
	// push.
	//
	// The server validates that the AGT's runner binding matches the runner
	// assigned to this job. Returns PERMISSION_DENIED if they do not match.
	// Returns FAILED_PRECONDITION if the serial is not greater than the current
	// serial. Returns INVALID_ARGUMENT if the lineage does not match the
	// existing state record.
	//
	// Maps to Terraform HTTP backend POST on the state address.
	//
	// Scope: `state:write` | Token types: `agt`
	PushState(context.Context, *connect.Request[v1.PushStateRequest]) (*connect.Response[v1.PushStateResponse], error)
	// LockState acquires an exclusive lock for the job's state. Terraform calls
	// this before plan/apply to prevent concurrent modifications.
	//
	// The server validates that the AGT's runner binding matches the runner
	// assigned to this job. Returns PERMISSION_DENIED if they do not match.
	// Returns FAILED_PRECONDITION if the state is already locked by a different
	// operation. The lock_id is generated by Terraform and must be passed to
	// UnlockState.
	//
	// Maps to Terraform HTTP backend POST on the lock address.
	//
	// Scope: `state:write` | Token types: `agt`
	LockState(context.Context, *connect.Request[v1.LockStateRequest]) (*connect.Response[v1.LockStateResponse], error)
	// UnlockState releases the exclusive lock on the job's state. The lock_id
	// must match the one used during LockState.
	//
	// The server validates that the AGT's runner binding matches the runner
	// assigned to this job. Returns PERMISSION_DENIED if they do not match.
	// Returns FAILED_PRECONDITION if the lock_id does not match the currently
	// held lock. Returns NOT_FOUND if no lock is held.
	//
	// Maps to Terraform HTTP backend POST on the unlock address.
	//
	// Scope: `state:write` | Token types: `agt`
	UnlockState(context.Context, *connect.Request[v1.UnlockStateRequest]) (*connect.Response[v1.UnlockStateResponse], error)
	// GetCurrentState retrieves the current state and lock info for a state
	// record. Returns the latest state data, serial, lineage, and any active
	// lock.
	//
	// Returns NOT_FOUND if the state record does not exist.
	//
	// Scope: `state:read`
	GetCurrentState(context.Context, *connect.Request[v1.GetCurrentStateRequest]) (*connect.Response[v1.GetCurrentStateResponse], error)
	// ListStates returns a paginated list of state records within the caller's
	// tenant. Use filters to scope by component, environment, or application.
	// Returns metadata only -- use GetCurrentState to fetch full state data.
	//
	// Scope: `state:read`
	ListStates(context.Context, *connect.Request[v1.ListStatesRequest]) (*connect.Response[v1.ListStatesResponse], error)
	// ListStateVersions returns a paginated history of state versions for a
	// state record. Returns metadata only (serial, md5, size) -- use
	// GetStateVersion to fetch the full state data at a specific serial.
	//
	// Returns NOT_FOUND if the state record does not exist.
	//
	// Scope: `state:read`
	ListStateVersions(context.Context, *connect.Request[v1.ListStateVersionsRequest]) (*connect.Response[v1.ListStateVersionsResponse], error)
	// GetStateVersion retrieves the full state data at a historical serial
	// number. Use ListStateVersions to discover available serials.
	//
	// Returns NOT_FOUND if the state record does not exist or if no version
	// with the specified serial exists for that state record.
	//
	// Scope: `state:read`
	GetStateVersion(context.Context, *connect.Request[v1.GetStateVersionRequest]) (*connect.Response[v1.GetStateVersionResponse], error)
	// ForceUnlockState forcefully releases a stuck lock on a state record.
	// Use this when a runner has crashed or become unreachable while holding
	// a lock, preventing subsequent deployments from proceeding.
	//
	// Returns NOT_FOUND if the state record does not exist.
	// Returns FAILED_PRECONDITION if the state has no active lock.
	// This action is logged in the audit trail.
	//
	// Scope: `state:admin`
	ForceUnlockState(context.Context, *connect.Request[v1.ForceUnlockStateRequest]) (*connect.Response[v1.ForceUnlockStateResponse], error)
	// DeleteState permanently deletes a state record and all its version
	// history. Fails if the state is currently locked -- force-unlock first.
	// This action cannot be undone.
	//
	// Returns NOT_FOUND if the state record does not exist.
	// Returns FAILED_PRECONDITION if the state is currently locked.
	//
	// Scope: `state:admin`
	DeleteState(context.Context, *connect.Request[v1.DeleteStateRequest]) (*connect.Response[v1.DeleteStateResponse], error)
}

// NewStateAPIClient constructs a client for the admiral.api.state.v1.StateAPI service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStateAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StateAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	stateAPIMethods := v1.File_admiral_api_state_v1_state_proto.Services().ByName("StateAPI").Methods()
	return &stateAPIClient{
		getState: connect.NewClient[v1.GetStateRequest, v1.GetStateResponse](
			httpClient,
			baseURL+StateAPIGetStateProcedure,
			connect.WithSchema(stateAPIMethods.ByName("GetState")),
			connect.WithClientOptions(opts...),
		),
		pushState: connect.NewClient[v1.PushStateRequest, v1.PushStateResponse](
			httpClient,
			baseURL+StateAPIPushStateProcedure,
			connect.WithSchema(stateAPIMethods.ByName("PushState")),
			connect.WithClientOptions(opts...),
		),
		lockState: connect.NewClient[v1.LockStateRequest, v1.LockStateResponse](
			httpClient,
			baseURL+StateAPILockStateProcedure,
			connect.WithSchema(stateAPIMethods.ByName("LockState")),
			connect.WithClientOptions(opts...),
		),
		unlockState: connect.NewClient[v1.UnlockStateRequest, v1.UnlockStateResponse](
			httpClient,
			baseURL+StateAPIUnlockStateProcedure,
			connect.WithSchema(stateAPIMethods.ByName("UnlockState")),
			connect.WithClientOptions(opts...),
		),
		getCurrentState: connect.NewClient[v1.GetCurrentStateRequest, v1.GetCurrentStateResponse](
			httpClient,
			baseURL+StateAPIGetCurrentStateProcedure,
			connect.WithSchema(stateAPIMethods.ByName("GetCurrentState")),
			connect.WithClientOptions(opts...),
		),
		listStates: connect.NewClient[v1.ListStatesRequest, v1.ListStatesResponse](
			httpClient,
			baseURL+StateAPIListStatesProcedure,
			connect.WithSchema(stateAPIMethods.ByName("ListStates")),
			connect.WithClientOptions(opts...),
		),
		listStateVersions: connect.NewClient[v1.ListStateVersionsRequest, v1.ListStateVersionsResponse](
			httpClient,
			baseURL+StateAPIListStateVersionsProcedure,
			connect.WithSchema(stateAPIMethods.ByName("ListStateVersions")),
			connect.WithClientOptions(opts...),
		),
		getStateVersion: connect.NewClient[v1.GetStateVersionRequest, v1.GetStateVersionResponse](
			httpClient,
			baseURL+StateAPIGetStateVersionProcedure,
			connect.WithSchema(stateAPIMethods.ByName("GetStateVersion")),
			connect.WithClientOptions(opts...),
		),
		forceUnlockState: connect.NewClient[v1.ForceUnlockStateRequest, v1.ForceUnlockStateResponse](
			httpClient,
			baseURL+StateAPIForceUnlockStateProcedure,
			connect.WithSchema(stateAPIMethods.ByName("ForceUnlockState")),
			connect.WithClientOptions(opts...),
		),
		deleteState: connect.NewClient[v1.DeleteStateRequest, v1.DeleteStateResponse](
			httpClient,
			baseURL+StateAPIDeleteStateProcedure,
			connect.WithSchema(stateAPIMethods.ByName("DeleteState")),
			connect.WithClientOptions(opts...),
		),
	}
}

// stateAPIClient implements StateAPIClient.
type stateAPIClient struct {
	getState          *connect.Client[v1.GetStateRequest, v1.GetStateResponse]
	pushState         *connect.Client[v1.PushStateRequest, v1.PushStateResponse]
	lockState         *connect.Client[v1.LockStateRequest, v1.LockStateResponse]
	unlockState       *connect.Client[v1.UnlockStateRequest, v1.UnlockStateResponse]
	getCurrentState   *connect.Client[v1.GetCurrentStateRequest, v1.GetCurrentStateResponse]
	listStates        *connect.Client[v1.ListStatesRequest, v1.ListStatesResponse]
	listStateVersions *connect.Client[v1.ListStateVersionsRequest, v1.ListStateVersionsResponse]
	getStateVersion   *connect.Client[v1.GetStateVersionRequest, v1.GetStateVersionResponse]
	forceUnlockState  *connect.Client[v1.ForceUnlockStateRequest, v1.ForceUnlockStateResponse]
	deleteState       *connect.Client[v1.DeleteStateRequest, v1.DeleteStateResponse]
}

// GetState calls admiral.api.state.v1.StateAPI.GetState.
func (c *stateAPIClient) GetState(ctx context.Context, req *connect.Request[v1.GetStateRequest]) (*connect.Response[v1.GetStateResponse], error) {
	return c.getState.CallUnary(ctx, req)
}

// PushState calls admiral.api.state.v1.StateAPI.PushState.
func (c *stateAPIClient) PushState(ctx context.Context, req *connect.Request[v1.PushStateRequest]) (*connect.Response[v1.PushStateResponse], error) {
	return c.pushState.CallUnary(ctx, req)
}

// LockState calls admiral.api.state.v1.StateAPI.LockState.
func (c *stateAPIClient) LockState(ctx context.Context, req *connect.Request[v1.LockStateRequest]) (*connect.Response[v1.LockStateResponse], error) {
	return c.lockState.CallUnary(ctx, req)
}

// UnlockState calls admiral.api.state.v1.StateAPI.UnlockState.
func (c *stateAPIClient) UnlockState(ctx context.Context, req *connect.Request[v1.UnlockStateRequest]) (*connect.Response[v1.UnlockStateResponse], error) {
	return c.unlockState.CallUnary(ctx, req)
}

// GetCurrentState calls admiral.api.state.v1.StateAPI.GetCurrentState.
func (c *stateAPIClient) GetCurrentState(ctx context.Context, req *connect.Request[v1.GetCurrentStateRequest]) (*connect.Response[v1.GetCurrentStateResponse], error) {
	return c.getCurrentState.CallUnary(ctx, req)
}

// ListStates calls admiral.api.state.v1.StateAPI.ListStates.
func (c *stateAPIClient) ListStates(ctx context.Context, req *connect.Request[v1.ListStatesRequest]) (*connect.Response[v1.ListStatesResponse], error) {
	return c.listStates.CallUnary(ctx, req)
}

// ListStateVersions calls admiral.api.state.v1.StateAPI.ListStateVersions.
func (c *stateAPIClient) ListStateVersions(ctx context.Context, req *connect.Request[v1.ListStateVersionsRequest]) (*connect.Response[v1.ListStateVersionsResponse], error) {
	return c.listStateVersions.CallUnary(ctx, req)
}

// GetStateVersion calls admiral.api.state.v1.StateAPI.GetStateVersion.
func (c *stateAPIClient) GetStateVersion(ctx context.Context, req *connect.Request[v1.GetStateVersionRequest]) (*connect.Response[v1.GetStateVersionResponse], error) {
	return c.getStateVersion.CallUnary(ctx, req)
}

// ForceUnlockState calls admiral.api.state.v1.StateAPI.ForceUnlockState.
func (c *stateAPIClient) ForceUnlockState(ctx context.Context, req *connect.Request[v1.ForceUnlockStateRequest]) (*connect.Response[v1.ForceUnlockStateResponse], error) {
	return c.forceUnlockState.CallUnary(ctx, req)
}

// DeleteState calls admiral.api.state.v1.StateAPI.DeleteState.
func (c *stateAPIClient) DeleteState(ctx context.Context, req *connect.Request[v1.DeleteStateRequest]) (*connect.Response[v1.DeleteStateResponse], error) {
	return c.deleteState.CallUnary(ctx, req)
}

// StateAPIHandler is an implementation of the admiral.api.state.v1.StateAPI service.
type StateAPIHandler interface {
	// GetState fetches the current state for a job's component + environment.
	// Returns empty data if no state exists yet (fresh init -- Terraform
	// handles this gracefully).
	//
	// The server validates that the AGT's runner binding matches the runner
	// assigned to this job. Returns PERMISSION_DENIED if they do not match.
	// Returns NOT_FOUND if the job does not exist or has been cancelled.
	//
	// Maps to Terraform HTTP backend GET on the state address.
	//
	// Scope: `state:read` | Token types: `agt`
	GetState(context.Context, *connect.Request[v1.GetStateRequest]) (*connect.Response[v1.GetStateResponse], error)
	// PushState stores a new state version after a successful apply. The server
	// validates the serial number (must be greater than current) and lineage
	// (must match if state already exists). Creates the state record on first
	// push.
	//
	// The server validates that the AGT's runner binding matches the runner
	// assigned to this job. Returns PERMISSION_DENIED if they do not match.
	// Returns FAILED_PRECONDITION if the serial is not greater than the current
	// serial. Returns INVALID_ARGUMENT if the lineage does not match the
	// existing state record.
	//
	// Maps to Terraform HTTP backend POST on the state address.
	//
	// Scope: `state:write` | Token types: `agt`
	PushState(context.Context, *connect.Request[v1.PushStateRequest]) (*connect.Response[v1.PushStateResponse], error)
	// LockState acquires an exclusive lock for the job's state. Terraform calls
	// this before plan/apply to prevent concurrent modifications.
	//
	// The server validates that the AGT's runner binding matches the runner
	// assigned to this job. Returns PERMISSION_DENIED if they do not match.
	// Returns FAILED_PRECONDITION if the state is already locked by a different
	// operation. The lock_id is generated by Terraform and must be passed to
	// UnlockState.
	//
	// Maps to Terraform HTTP backend POST on the lock address.
	//
	// Scope: `state:write` | Token types: `agt`
	LockState(context.Context, *connect.Request[v1.LockStateRequest]) (*connect.Response[v1.LockStateResponse], error)
	// UnlockState releases the exclusive lock on the job's state. The lock_id
	// must match the one used during LockState.
	//
	// The server validates that the AGT's runner binding matches the runner
	// assigned to this job. Returns PERMISSION_DENIED if they do not match.
	// Returns FAILED_PRECONDITION if the lock_id does not match the currently
	// held lock. Returns NOT_FOUND if no lock is held.
	//
	// Maps to Terraform HTTP backend POST on the unlock address.
	//
	// Scope: `state:write` | Token types: `agt`
	UnlockState(context.Context, *connect.Request[v1.UnlockStateRequest]) (*connect.Response[v1.UnlockStateResponse], error)
	// GetCurrentState retrieves the current state and lock info for a state
	// record. Returns the latest state data, serial, lineage, and any active
	// lock.
	//
	// Returns NOT_FOUND if the state record does not exist.
	//
	// Scope: `state:read`
	GetCurrentState(context.Context, *connect.Request[v1.GetCurrentStateRequest]) (*connect.Response[v1.GetCurrentStateResponse], error)
	// ListStates returns a paginated list of state records within the caller's
	// tenant. Use filters to scope by component, environment, or application.
	// Returns metadata only -- use GetCurrentState to fetch full state data.
	//
	// Scope: `state:read`
	ListStates(context.Context, *connect.Request[v1.ListStatesRequest]) (*connect.Response[v1.ListStatesResponse], error)
	// ListStateVersions returns a paginated history of state versions for a
	// state record. Returns metadata only (serial, md5, size) -- use
	// GetStateVersion to fetch the full state data at a specific serial.
	//
	// Returns NOT_FOUND if the state record does not exist.
	//
	// Scope: `state:read`
	ListStateVersions(context.Context, *connect.Request[v1.ListStateVersionsRequest]) (*connect.Response[v1.ListStateVersionsResponse], error)
	// GetStateVersion retrieves the full state data at a historical serial
	// number. Use ListStateVersions to discover available serials.
	//
	// Returns NOT_FOUND if the state record does not exist or if no version
	// with the specified serial exists for that state record.
	//
	// Scope: `state:read`
	GetStateVersion(context.Context, *connect.Request[v1.GetStateVersionRequest]) (*connect.Response[v1.GetStateVersionResponse], error)
	// ForceUnlockState forcefully releases a stuck lock on a state record.
	// Use this when a runner has crashed or become unreachable while holding
	// a lock, preventing subsequent deployments from proceeding.
	//
	// Returns NOT_FOUND if the state record does not exist.
	// Returns FAILED_PRECONDITION if the state has no active lock.
	// This action is logged in the audit trail.
	//
	// Scope: `state:admin`
	ForceUnlockState(context.Context, *connect.Request[v1.ForceUnlockStateRequest]) (*connect.Response[v1.ForceUnlockStateResponse], error)
	// DeleteState permanently deletes a state record and all its version
	// history. Fails if the state is currently locked -- force-unlock first.
	// This action cannot be undone.
	//
	// Returns NOT_FOUND if the state record does not exist.
	// Returns FAILED_PRECONDITION if the state is currently locked.
	//
	// Scope: `state:admin`
	DeleteState(context.Context, *connect.Request[v1.DeleteStateRequest]) (*connect.Response[v1.DeleteStateResponse], error)
}

// NewStateAPIHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStateAPIHandler(svc StateAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	stateAPIMethods := v1.File_admiral_api_state_v1_state_proto.Services().ByName("StateAPI").Methods()
	stateAPIGetStateHandler := connect.NewUnaryHandler(
		StateAPIGetStateProcedure,
		svc.GetState,
		connect.WithSchema(stateAPIMethods.ByName("GetState")),
		connect.WithHandlerOptions(opts...),
	)
	stateAPIPushStateHandler := connect.NewUnaryHandler(
		StateAPIPushStateProcedure,
		svc.PushState,
		connect.WithSchema(stateAPIMethods.ByName("PushState")),
		connect.WithHandlerOptions(opts...),
	)
	stateAPILockStateHandler := connect.NewUnaryHandler(
		StateAPILockStateProcedure,
		svc.LockState,
		connect.WithSchema(stateAPIMethods.ByName("LockState")),
		connect.WithHandlerOptions(opts...),
	)
	stateAPIUnlockStateHandler := connect.NewUnaryHandler(
		StateAPIUnlockStateProcedure,
		svc.UnlockState,
		connect.WithSchema(stateAPIMethods.ByName("UnlockState")),
		connect.WithHandlerOptions(opts...),
	)
	stateAPIGetCurrentStateHandler := connect.NewUnaryHandler(
		StateAPIGetCurrentStateProcedure,
		svc.GetCurrentState,
		connect.WithSchema(stateAPIMethods.ByName("GetCurrentState")),
		connect.WithHandlerOptions(opts...),
	)
	stateAPIListStatesHandler := connect.NewUnaryHandler(
		StateAPIListStatesProcedure,
		svc.ListStates,
		connect.WithSchema(stateAPIMethods.ByName("ListStates")),
		connect.WithHandlerOptions(opts...),
	)
	stateAPIListStateVersionsHandler := connect.NewUnaryHandler(
		StateAPIListStateVersionsProcedure,
		svc.ListStateVersions,
		connect.WithSchema(stateAPIMethods.ByName("ListStateVersions")),
		connect.WithHandlerOptions(opts...),
	)
	stateAPIGetStateVersionHandler := connect.NewUnaryHandler(
		StateAPIGetStateVersionProcedure,
		svc.GetStateVersion,
		connect.WithSchema(stateAPIMethods.ByName("GetStateVersion")),
		connect.WithHandlerOptions(opts...),
	)
	stateAPIForceUnlockStateHandler := connect.NewUnaryHandler(
		StateAPIForceUnlockStateProcedure,
		svc.ForceUnlockState,
		connect.WithSchema(stateAPIMethods.ByName("ForceUnlockState")),
		connect.WithHandlerOptions(opts...),
	)
	stateAPIDeleteStateHandler := connect.NewUnaryHandler(
		StateAPIDeleteStateProcedure,
		svc.DeleteState,
		connect.WithSchema(stateAPIMethods.ByName("DeleteState")),
		connect.WithHandlerOptions(opts...),
	)
	return "/admiral.api.state.v1.StateAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StateAPIGetStateProcedure:
			stateAPIGetStateHandler.ServeHTTP(w, r)
		case StateAPIPushStateProcedure:
			stateAPIPushStateHandler.ServeHTTP(w, r)
		case StateAPILockStateProcedure:
			stateAPILockStateHandler.ServeHTTP(w, r)
		case StateAPIUnlockStateProcedure:
			stateAPIUnlockStateHandler.ServeHTTP(w, r)
		case StateAPIGetCurrentStateProcedure:
			stateAPIGetCurrentStateHandler.ServeHTTP(w, r)
		case StateAPIListStatesProcedure:
			stateAPIListStatesHandler.ServeHTTP(w, r)
		case StateAPIListStateVersionsProcedure:
			stateAPIListStateVersionsHandler.ServeHTTP(w, r)
		case StateAPIGetStateVersionProcedure:
			stateAPIGetStateVersionHandler.ServeHTTP(w, r)
		case StateAPIForceUnlockStateProcedure:
			stateAPIForceUnlockStateHandler.ServeHTTP(w, r)
		case StateAPIDeleteStateProcedure:
			stateAPIDeleteStateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStateAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedStateAPIHandler struct{}

func (UnimplementedStateAPIHandler) GetState(context.Context, *connect.Request[v1.GetStateRequest]) (*connect.Response[v1.GetStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.state.v1.StateAPI.GetState is not implemented"))
}

func (UnimplementedStateAPIHandler) PushState(context.Context, *connect.Request[v1.PushStateRequest]) (*connect.Response[v1.PushStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.state.v1.StateAPI.PushState is not implemented"))
}

func (UnimplementedStateAPIHandler) LockState(context.Context, *connect.Request[v1.LockStateRequest]) (*connect.Response[v1.LockStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.state.v1.StateAPI.LockState is not implemented"))
}

func (UnimplementedStateAPIHandler) UnlockState(context.Context, *connect.Request[v1.UnlockStateRequest]) (*connect.Response[v1.UnlockStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.state.v1.StateAPI.UnlockState is not implemented"))
}

func (UnimplementedStateAPIHandler) GetCurrentState(context.Context, *connect.Request[v1.GetCurrentStateRequest]) (*connect.Response[v1.GetCurrentStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.state.v1.StateAPI.GetCurrentState is not implemented"))
}

func (UnimplementedStateAPIHandler) ListStates(context.Context, *connect.Request[v1.ListStatesRequest]) (*connect.Response[v1.ListStatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.state.v1.StateAPI.ListStates is not implemented"))
}

func (UnimplementedStateAPIHandler) ListStateVersions(context.Context, *connect.Request[v1.ListStateVersionsRequest]) (*connect.Response[v1.ListStateVersionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.state.v1.StateAPI.ListStateVersions is not implemented"))
}

func (UnimplementedStateAPIHandler) GetStateVersion(context.Context, *connect.Request[v1.GetStateVersionRequest]) (*connect.Response[v1.GetStateVersionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.state.v1.StateAPI.GetStateVersion is not implemented"))
}

func (UnimplementedStateAPIHandler) ForceUnlockState(context.Context, *connect.Request[v1.ForceUnlockStateRequest]) (*connect.Response[v1.ForceUnlockStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.state.v1.StateAPI.ForceUnlockState is not implemented"))
}

func (UnimplementedStateAPIHandler) DeleteState(context.Context, *connect.Request[v1.DeleteStateRequest]) (*connect.Response[v1.DeleteStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.state.v1.StateAPI.DeleteState is not implemented"))
}
