// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: admiral/api/connection/v1/connection.proto

package connectionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConnectionAPI_CreateConnection_FullMethodName = "/admiral.api.connection.v1.ConnectionAPI/CreateConnection"
	ConnectionAPI_GetConnection_FullMethodName    = "/admiral.api.connection.v1.ConnectionAPI/GetConnection"
	ConnectionAPI_ListConnections_FullMethodName  = "/admiral.api.connection.v1.ConnectionAPI/ListConnections"
	ConnectionAPI_UpdateConnection_FullMethodName = "/admiral.api.connection.v1.ConnectionAPI/UpdateConnection"
	ConnectionAPI_DeleteConnection_FullMethodName = "/admiral.api.connection.v1.ConnectionAPI/DeleteConnection"
	ConnectionAPI_TestConnection_FullMethodName   = "/admiral.api.connection.v1.ConnectionAPI/TestConnection"
)

// ConnectionAPIClient is the client API for ConnectionAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConnectionAPI manages credentials for accessing external systems.
//
// A connection stores the authentication configuration needed to reach a remote
// system -- a Git host, Helm repository, OCI registry, Terraform registry, or
// cloud provider. Connections are tenant-scoped and referenced by sources when
// fetching artifacts.
//
// Sensitive credential fields (tokens, keys, secrets) are write-only: they are
// accepted on create/update but never returned in API responses. GET and List
// operations return connection metadata and status only.
//
// For cloud registries (ECR, GAR, ACR), OIDC workload identity federation is
// the recommended approach. Admiral acts as an OIDC identity provider -- the
// customer configures their cloud IAM to trust Admiral's issuer with their
// tenant_id claim. No long-lived secrets are stored in Admiral. Static cloud
// credentials are supported for legacy or airgapped environments but are
// discouraged and may be restricted via tenant-level policy in the future.
type ConnectionAPIClient interface {
	// CreateConnection creates a new connection within the caller's tenant.
	//
	// The connection type and auth config must match -- for example, a GIT_TOKEN
	// connection requires a GitTokenAuth config. The server validates connectivity
	// on creation when possible and sets the initial status accordingly.
	//
	// Scope: `connection:write`
	CreateConnection(ctx context.Context, in *CreateConnectionRequest, opts ...grpc.CallOption) (*CreateConnectionResponse, error)
	// GetConnection retrieves a connection by ID.
	//
	// Returns connection metadata and status. Sensitive credential fields are
	// never included in the response.
	//
	// Scope: `connection:read`
	GetConnection(ctx context.Context, in *GetConnectionRequest, opts ...grpc.CallOption) (*GetConnectionResponse, error)
	// ListConnections returns a paginated list of connections within the caller's
	// tenant. Sensitive credential fields are never included.
	//
	// Scope: `connection:read`
	ListConnections(ctx context.Context, in *ListConnectionsRequest, opts ...grpc.CallOption) (*ListConnectionsResponse, error)
	// UpdateConnection updates a connection's mutable fields.
	// Use the `update_mask` to specify which fields to update.
	//
	// When updating auth_config, the entire auth config is replaced -- partial
	// updates within the auth config oneof are not supported. Omitting auth_config
	// from the update_mask leaves credentials unchanged.
	//
	// Scope: `connection:write`
	UpdateConnection(ctx context.Context, in *UpdateConnectionRequest, opts ...grpc.CallOption) (*UpdateConnectionResponse, error)
	// DeleteConnection permanently deletes a connection. Fails if any sources
	// still reference this connection -- remove or reassign those sources first.
	// This action cannot be undone.
	//
	// Scope: `connection:write`
	DeleteConnection(ctx context.Context, in *DeleteConnectionRequest, opts ...grpc.CallOption) (*DeleteConnectionResponse, error)
	// TestConnection validates that the stored credentials can successfully
	// authenticate to the remote system. Updates the connection's status and
	// last_tested_at fields based on the result.
	//
	// This operation makes a network call to the external system and may take
	// several seconds depending on the remote endpoint.
	//
	// Scope: `connection:write`
	TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error)
}

type connectionAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectionAPIClient(cc grpc.ClientConnInterface) ConnectionAPIClient {
	return &connectionAPIClient{cc}
}

func (c *connectionAPIClient) CreateConnection(ctx context.Context, in *CreateConnectionRequest, opts ...grpc.CallOption) (*CreateConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateConnectionResponse)
	err := c.cc.Invoke(ctx, ConnectionAPI_CreateConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionAPIClient) GetConnection(ctx context.Context, in *GetConnectionRequest, opts ...grpc.CallOption) (*GetConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectionResponse)
	err := c.cc.Invoke(ctx, ConnectionAPI_GetConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionAPIClient) ListConnections(ctx context.Context, in *ListConnectionsRequest, opts ...grpc.CallOption) (*ListConnectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConnectionsResponse)
	err := c.cc.Invoke(ctx, ConnectionAPI_ListConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionAPIClient) UpdateConnection(ctx context.Context, in *UpdateConnectionRequest, opts ...grpc.CallOption) (*UpdateConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConnectionResponse)
	err := c.cc.Invoke(ctx, ConnectionAPI_UpdateConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionAPIClient) DeleteConnection(ctx context.Context, in *DeleteConnectionRequest, opts ...grpc.CallOption) (*DeleteConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConnectionResponse)
	err := c.cc.Invoke(ctx, ConnectionAPI_DeleteConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionAPIClient) TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestConnectionResponse)
	err := c.cc.Invoke(ctx, ConnectionAPI_TestConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectionAPIServer is the server API for ConnectionAPI service.
// All implementations should embed UnimplementedConnectionAPIServer
// for forward compatibility.
//
// ConnectionAPI manages credentials for accessing external systems.
//
// A connection stores the authentication configuration needed to reach a remote
// system -- a Git host, Helm repository, OCI registry, Terraform registry, or
// cloud provider. Connections are tenant-scoped and referenced by sources when
// fetching artifacts.
//
// Sensitive credential fields (tokens, keys, secrets) are write-only: they are
// accepted on create/update but never returned in API responses. GET and List
// operations return connection metadata and status only.
//
// For cloud registries (ECR, GAR, ACR), OIDC workload identity federation is
// the recommended approach. Admiral acts as an OIDC identity provider -- the
// customer configures their cloud IAM to trust Admiral's issuer with their
// tenant_id claim. No long-lived secrets are stored in Admiral. Static cloud
// credentials are supported for legacy or airgapped environments but are
// discouraged and may be restricted via tenant-level policy in the future.
type ConnectionAPIServer interface {
	// CreateConnection creates a new connection within the caller's tenant.
	//
	// The connection type and auth config must match -- for example, a GIT_TOKEN
	// connection requires a GitTokenAuth config. The server validates connectivity
	// on creation when possible and sets the initial status accordingly.
	//
	// Scope: `connection:write`
	CreateConnection(context.Context, *CreateConnectionRequest) (*CreateConnectionResponse, error)
	// GetConnection retrieves a connection by ID.
	//
	// Returns connection metadata and status. Sensitive credential fields are
	// never included in the response.
	//
	// Scope: `connection:read`
	GetConnection(context.Context, *GetConnectionRequest) (*GetConnectionResponse, error)
	// ListConnections returns a paginated list of connections within the caller's
	// tenant. Sensitive credential fields are never included.
	//
	// Scope: `connection:read`
	ListConnections(context.Context, *ListConnectionsRequest) (*ListConnectionsResponse, error)
	// UpdateConnection updates a connection's mutable fields.
	// Use the `update_mask` to specify which fields to update.
	//
	// When updating auth_config, the entire auth config is replaced -- partial
	// updates within the auth config oneof are not supported. Omitting auth_config
	// from the update_mask leaves credentials unchanged.
	//
	// Scope: `connection:write`
	UpdateConnection(context.Context, *UpdateConnectionRequest) (*UpdateConnectionResponse, error)
	// DeleteConnection permanently deletes a connection. Fails if any sources
	// still reference this connection -- remove or reassign those sources first.
	// This action cannot be undone.
	//
	// Scope: `connection:write`
	DeleteConnection(context.Context, *DeleteConnectionRequest) (*DeleteConnectionResponse, error)
	// TestConnection validates that the stored credentials can successfully
	// authenticate to the remote system. Updates the connection's status and
	// last_tested_at fields based on the result.
	//
	// This operation makes a network call to the external system and may take
	// several seconds depending on the remote endpoint.
	//
	// Scope: `connection:write`
	TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionResponse, error)
}

// UnimplementedConnectionAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectionAPIServer struct{}

func (UnimplementedConnectionAPIServer) CreateConnection(context.Context, *CreateConnectionRequest) (*CreateConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateConnection not implemented")
}
func (UnimplementedConnectionAPIServer) GetConnection(context.Context, *GetConnectionRequest) (*GetConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnection not implemented")
}
func (UnimplementedConnectionAPIServer) ListConnections(context.Context, *ListConnectionsRequest) (*ListConnectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConnections not implemented")
}
func (UnimplementedConnectionAPIServer) UpdateConnection(context.Context, *UpdateConnectionRequest) (*UpdateConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConnection not implemented")
}
func (UnimplementedConnectionAPIServer) DeleteConnection(context.Context, *DeleteConnectionRequest) (*DeleteConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConnection not implemented")
}
func (UnimplementedConnectionAPIServer) TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestConnection not implemented")
}
func (UnimplementedConnectionAPIServer) testEmbeddedByValue() {}

// UnsafeConnectionAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectionAPIServer will
// result in compilation errors.
type UnsafeConnectionAPIServer interface {
	mustEmbedUnimplementedConnectionAPIServer()
}

func RegisterConnectionAPIServer(s grpc.ServiceRegistrar, srv ConnectionAPIServer) {
	// If the following call panics, it indicates UnimplementedConnectionAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnectionAPI_ServiceDesc, srv)
}

func _ConnectionAPI_CreateConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionAPIServer).CreateConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionAPI_CreateConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionAPIServer).CreateConnection(ctx, req.(*CreateConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionAPI_GetConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionAPIServer).GetConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionAPI_GetConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionAPIServer).GetConnection(ctx, req.(*GetConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionAPI_ListConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionAPIServer).ListConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionAPI_ListConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionAPIServer).ListConnections(ctx, req.(*ListConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionAPI_UpdateConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionAPIServer).UpdateConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionAPI_UpdateConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionAPIServer).UpdateConnection(ctx, req.(*UpdateConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionAPI_DeleteConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionAPIServer).DeleteConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionAPI_DeleteConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionAPIServer).DeleteConnection(ctx, req.(*DeleteConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionAPI_TestConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionAPIServer).TestConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionAPI_TestConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionAPIServer).TestConnection(ctx, req.(*TestConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnectionAPI_ServiceDesc is the grpc.ServiceDesc for ConnectionAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectionAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admiral.api.connection.v1.ConnectionAPI",
	HandlerType: (*ConnectionAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConnection",
			Handler:    _ConnectionAPI_CreateConnection_Handler,
		},
		{
			MethodName: "GetConnection",
			Handler:    _ConnectionAPI_GetConnection_Handler,
		},
		{
			MethodName: "ListConnections",
			Handler:    _ConnectionAPI_ListConnections_Handler,
		},
		{
			MethodName: "UpdateConnection",
			Handler:    _ConnectionAPI_UpdateConnection_Handler,
		},
		{
			MethodName: "DeleteConnection",
			Handler:    _ConnectionAPI_DeleteConnection_Handler,
		},
		{
			MethodName: "TestConnection",
			Handler:    _ConnectionAPI_TestConnection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admiral/api/connection/v1/connection.proto",
}
